numbersprotocol/capture-cam

src/app/app-routing.module.ts
src/app/components/header/header.component.html
src/app/components/header/header.component.spec.ts
src/app/components/header/header.component.ts
src/app/components/header/header.module.ts
src/app/pages/about/about-routing.module.ts
src/app/pages/about/about.module.ts
src/app/pages/about/about.page.html
src/app/pages/about/about.page.ts
src/app/pages/defaultinformationprovider/defaultinformationprovider-routing.module.ts
src/app/pages/defaultinformationprovider/defaultinformationprovider.module.ts
src/app/pages/defaultinformationprovider/defaultinformationprovider.page.html
src/app/pages/defaultinformationprovider/defaultinformationprovider.page.ts
src/app/pages/defaultsignature/defaultsignature-routing.module.ts
src/app/pages/defaultsignature/defaultsignature.module.ts
src/app/pages/defaultsignature/defaultsignature.page.html
src/app/pages/defaultsignature/defaultsignature.page.ts
src/app/pages/general/general-routing.module.ts
src/app/pages/general/general.module.ts
src/app/pages/general/general.page.html
src/app/pages/general/general.page.ts
src/app/pages/storage/storage.page.html
src/assets/i18n/en-us.json

add setting drawer

---

src/app/components/header/header.component.html
src/app/components/header/header.component.ts
src/app/pages/storage/storage.page.html

fix  top bar PR 把 drawer 的 header 蓋掉了的問題

fix head bar

---

src/app/pages/storage/storage.page.ts

Sort proof by timestamp in proofsWithRaw for the tag page to display with correct ordering

---

src/global.scss

fix ios  iphoneX header Occlude

---

src/app/pages/home/inbox/inbox.page.html
src/app/pages/home/inbox/inbox.page.scss
src/app/services/publisher/numbers-storage/numbers-storage-api.service.ts

Show 'Nothing Here' on inbox page when no item to show. #207

---

src/app/services/blocking-action/blocking-action.service.spec.ts
src/app/services/blocking-action/blocking-action.service.ts

Refactor `BlockingActionService` with fully covered tests.

Refactor Blocking Action Service

---

src/app/pages/home/asset/sending-post-capture/sending-post-capture.page.scss

fix send postCapture

---

src/app/pages/home/asset/asset.page.html
src/app/pages/home/asset/asset.page.scss
src/app/pages/home/home.page.scss
src/app/shared/post-capture-card/post-capture-card.component.scss
src/global.scss

fix issue #289 (ios 13.7 iphone 6s plus 上方多出一塊白色方塊)
fix issue #285 (Postcapture wall Change the load img default Color )
fix issue #284 (capture wall Unified font size)
fix issue #282 (Cannot Scroll on Asset Page )
fix issue #259 (end-button)

Fix UI beta7.2

---

src/app/services/collector/facts/capacitor-facts-provider/capacitor-facts-provider.service.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

A missed feature suggestion for #267.
```
sherry  6:23 PM
@James 這個 proposal 我覺得 OK，另外也建議加上訊息的 dismiss button。
```

Add dismiss button for geolocation error message.

---

src/app/pages/home/home.page.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

The minimum workaround for #291 .

Feature postcapture not display workaround

---

src/app/pages/home/inbox/inbox.page.html
src/app/pages/home/inbox/inbox.page.scss
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

See #335. The fix has been tested on web and Exodus 1s.

Rename nothing-here to empty-inbox

---

src/app/pages/home/asset/asset.page.html

A very simple fix for the misplaced button on iOS Webview and Safari.

Fix webkit browser view-all button out of place

---

src/app/pages/home/home.page.html
src/app/pages/home/home.page.ts

The Capture tab will show the latest captures first.

Sort descending for captures.

---

src/app/services/collector/facts/capacitor-facts-provider/capacitor-facts-provider.service.ts

Collect the complete device info, including:
```typescript
{
[DefaultFactId.DEVICE_NAME]: deviceInfo?.model,
[DefaultFactId.GEOLOCATION_LATITUDE]: locationInfo?.coords.latitude,
[DefaultFactId.GEOLOCATION_LONGITUDE]: locationInfo?.coords.longitude,
USER_DEVICE_NAME: deviceInfo?.name,
PLATFORM: deviceInfo?.platform,
UUID: deviceInfo?.uuid,
APP_VERSION: deviceInfo?.appVersion,
APP_BUILD: deviceInfo?.appBuild,
APP_ID: deviceInfo?.appId,
APP_NAME: deviceInfo?.appName,
OPERATING_SYSTEM: deviceInfo?.operatingSystem,
OS_VERSION: deviceInfo?.osVersion,
MANUFACTURER: deviceInfo?.manufacturer,
IS_VIRTUAL: deviceInfo?.isVirtual,
MEM_USED: deviceInfo?.memUsed,
DISK_FREE: deviceInfo?.diskFree,
DISK_TOTAL: deviceInfo?.diskTotal,
BETTERY_LEVEL: deviceInfo?.batteryLevel,
IS_CHARGING: …
```

Collect complete device info.

---

src/app/services/dia-backend/asset/dia-backend-asset-repository.service.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

See #363. This PR has been tested on Exodus 1s.

Show Migrating Snackbar

---

src/app/services/dia-backend/auth/dia-backend-auth.service.ts
src/app/services/dia-backend/notification/dia-backend-notification.service.ts
src/app/services/push-notification/push-notification.service.ts

- Device info and FCM token not registered to DIA backend during first-time using the App.
- iOS only: push notification permission error during first-time using the App..
- Android only: tapping on push notification causes untranslated message shown on local notification.

Fix push notification issues

---

src/app/pages/tutorial/tutorial.page.html
src/app/pages/tutorial/tutorial.page.scss

fix font &  position

---

ios/App/App/Info.plist

Add manual en and zh_TW i18n for iOS

---

src/app/pages/home/inbox/inbox.page.scss

fix ios Empty Inbox position

---

src/app/pages/login/login.page.html
src/app/pages/login/login.page.ts
src/app/services/dia-backend/auth/dia-backend-auth.service.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

Show a resend activation email button when login fails with user-not-active error.

---

src/app/pages/home/asset/sending-post-capture/sending-post-capture.page.html
src/app/shared/post-capture-card/post-capture-card.component.html
src/app/shared/post-capture-card/post-capture-card.component.ts

Hide share button on PostCapture preview

---

src/app/pages/home/home.page.html
src/app/pages/home/home.page.ts

Improve UX by showing new photo directly after captured.

Show photo directly after captured.

---

src/app/app.component.spec.ts
src/app/features/home/capture-tab/capture-tab.component.html
src/app/features/home/capture-tab/capture-tab.component.scss
src/app/features/home/capture-tab/capture-tab.component.spec.ts
src/app/features/home/capture-tab/capture-tab.component.ts
src/app/features/home/home.module.ts
src/app/features/home/home.page.html
src/app/features/home/home.page.scss
src/app/features/home/home.page.spec.ts
src/app/features/home/home.page.ts
src/app/shared/core/post-capture-card/post-capture-card.component.spec.ts
src/app/shared/shared-testing.module.ts
src/theme/variables.scss

- Implement camera-only functionality.
- Create a standalone component for Capture Tab.
- Update Ionic Theme.
- Fix or suppress unit tests.

Rebuild Capture: Step A (Camera Only)

---

src/app/app.component.ts
src/app/features/home/capture-tab/uploading-bar/uploading-bar.component.html
src/app/features/home/capture-tab/uploading-bar/uploading-bar.component.scss
src/app/features/home/capture-tab/uploading-bar/uploading-bar.component.ts
src/app/shared/core/capacitor-plugins/capacitor-plugins-testing.module.ts
src/app/shared/core/capacitor-plugins/capacitor-plugins.module.ts
src/app/shared/core/capacitor-plugins/mock-network-plugin.ts
src/app/shared/services/dia-backend/asset/uploading/dia-backend-asset-uploading.service.ts
src/app/shared/services/network/network.service.spec.ts
src/app/shared/services/network/network.service.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

- Save pausing status to preference.
- Combine user-pausing and network connection to determine upload pausing/resuming.
- Infinite retry with exponentially incremental interval.

Rebuild Capture - Step D2-3 (Resuming Upload After Reconnecting)

---

src/app/features/home/capture-tab/capture-details/capture-details.page.html
src/app/features/home/capture-tab/capture-details/capture-details.page.ts

- Only show send button if the proof is registered

Rebuild Capture - Step D2-4

---

src/app/app.component.ts
src/app/features/about/about.page.html
src/app/features/home/capture-tab/capture-tab.component.ts
src/app/features/home/home.page.ts
src/app/shared/core/post-capture-card/options-menu/options-menu.component.html
src/app/shared/core/post-capture-card/options-menu/options-menu.component.ts
src/app/shared/core/post-capture-card/post-capture-card.component.html
src/app/shared/core/post-capture-card/post-capture-card.component.ts
src/app/shared/services/dia-backend/asset/dia-backend-asset-repository.service.ts
src/app/shared/services/migration/migration.service.spec.ts
src/app/shared/services/migration/migration.service.ts
src/app/shared/services/repositories/proof/proof-repository.service.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

- Handling version update with data migration.
- Store previous version in local preference.
- Show "contact us" on about page.
- Remove delete button on PostCapture card.

Rebuild Capture - H2 (Version Update)

---

src/app/app.component.spec.ts
src/app/app.component.ts
src/app/features/home/home.page.ts
src/app/shared/services/dia-backend/auth/dia-backend-auth.service.ts
src/app/shared/services/migration/migration.service.ts

Migrate the `IS_ONBOARDING` preference in `OnboardingService` to `HAS_SHOWN_TUTORIAL` and `HAS_PREFETCHED_DIA_BACKEND_ASSETS` preferences to avoid showing these pages again if the user has logged in before.

Show prefetching/tutorial pages only on first time login.

---

src/app/shared/core/migrating-dialog/migrating-dialog.component.html
src/app/shared/core/migrating-dialog/migrating-dialog.component.scss
src/app/shared/core/migrating-dialog/migrating-dialog.component.spec.ts
src/app/shared/core/migrating-dialog/migrating-dialog.component.ts
src/app/shared/services/capture/capture.service.ts
src/app/shared/services/database/table/capacitor-filesystem-table/capacitor-filesystem-table.spec.ts
src/app/shared/services/database/table/capacitor-filesystem-table/capacitor-filesystem-table.ts
src/app/shared/services/database/table/table.ts
src/app/shared/services/dia-backend/asset/uploading/dia-backend-asset-uploading.service.ts
src/app/shared/services/migration/migration.service.ts
src/app/shared/services/repositories/proof/proof-repository.service.spec.ts
src/app/shared/services/repositories/proof/proof-repository.service.ts
src/app/shared/shared.module.ts

- Migrating diaBackendAssetId from backend to ProofRepository in 0.15.0 migration
- Show indetermined progress bar in dialog

Migrating diaBackendAssetId

---

src/app/features/home/home.page.html

Change tab labels to icons

---

src/app/features/home/home.page.ts

Save hasPrefetched as true if user choose to skip

---

src/app/features/home/home.page.html
src/app/features/home/home.page.scss
src/app/features/home/home.page.ts

Change the interaction to the bottom

---

src/app/features/home/home.page.ts
src/app/shared/services/dia-backend/asset/dia-backend-asset-repository.service.ts

Fix unintended prefetching

---

src/app/shared/services/share/share.service.ts

The change is implemented on a diverged release branch `release-0.16.7` and it should be merged back to develop.

Remove new year frame when sharing

---

src/global.scss

Feature add safearea

---

src/app/features/home/capture-tab/capture-details/capture-details.page.html
src/app/features/home/capture-tab/capture-details/capture-details.page.ts
src/app/features/home/capture-tab/capture-details/options-menu/options-menu.component.html
src/app/features/home/capture-tab/capture-details/options-menu/options-menu.component.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

- Add: Share moment on options menu
- Add: Send moment on options menu
- Add: Delete moment on options menu
- Add: View blockchain certificate on options menu
- Remove: view blockchain certificate on media ID

Adjust options on the menu of capture-details.

---

src/app/shared/core/post-capture-card/post-capture-card.component.html
src/app/shared/core/post-capture-card/post-capture-card.component.scss

Reduce the size from 20px to 16px.

Reduce the size of PostCapture sender email.

---

src/app/features/home/onboarding/prefetching-dialog/prefetching-dialog.component.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

According to the discussion on Slack
> Tammy  12:02 PM
> @seanwu1105  請改成
> ```
> Fail to pull old Moments
> 載入瞬時影像失敗
> ```

Update error dialog title on prefetching.

---

src/app/shared/core/post-capture-card/options-menu/options-menu.component.html
src/app/shared/core/post-capture-card/options-menu/options-menu.component.spec.ts
src/app/shared/core/post-capture-card/options-menu/options-menu.component.ts
src/app/shared/core/post-capture-card/post-capture-card.component.ts

Feature post capture option

---

src/app/features/home/capture-tab/capture-tab.component.scss
src/app/features/home/home.page.html

- Update the position and size of the capture status-preview icons.
- Disable pagination of the tabs on home page.

Update capture status-preview icons

---

src/app/features/home/capture-tab/capture-details/capture-details.page.html
src/app/features/home/capture-tab/capture-details/capture-details.page.scss
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

According to the discussion on Slack:
> @tammyyang 11:46 AM: 
> F. 細節調整
> ...
> b. Capture 的 Moment Details 字拿掉

Remove the title on CaptureDetailsPage.

---

.github/workflows/pre-release.yml

Add iOS build number to release slack message

---

src/app/features/profile/profile.page.ts
src/app/shared/services/dia-backend/auth/dia-backend-auth.service.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

- Add confirm alert before lgout
- Catch error 401 on logout

Add confirm alert before logout and catch error 401 on logout.

---

src/app/features/login/login.page.html
src/app/features/login/login.page.ts
src/app/features/profile/profile.page.html
src/app/features/profile/profile.page.scss
src/app/features/profile/profile.page.ts
src/app/shared/services/dia-backend/auth/dia-backend-auth.service.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

Implement the password-resetting dialog.

---

src/app/features/profile/profile.page.html
src/app/features/profile/profile.page.ts
src/app/shared/services/dia-backend/auth/dia-backend-auth.service.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

See #389. The PR has been tested on Exodus 1 and Brave browser.

Add username editing feature.

---

src/app/features/home/capture-tab/capture-tab.component.html
src/app/features/home/capture-tab/capture-tab.component.scss
src/app/features/home/capture-tab/capture-tab.component.ts
src/app/features/home/home.page.html
src/app/features/home/home.page.scss

1. 在 Capture 頁面加入上方的 profile 資訊並且可以修改 （目前只有Name ，照片(等有Api)之後作）
2. 下方 icon 調整為兩個 (暫時看不見 PostCapture)

UI grid post capture

---

src/app/features/home/capture-tab/capture-details/capture-details.page.html
src/app/features/home/capture-tab/capture-details/capture-details.page.ts

See #367. This PR has been tested on Exodus 1 and Brave browser.

Display username on Capture details page

---

src/app/features/home/post-capture-tab/post-capture-details/post-capture-details.page.ts

See [the discussion on Slack](https://dt42-numbers.slack.com/archives/CS29L7Z5H/p1615441103058900).

Add the missing translation on PostCaptureDetailsPage.

---

src/app/features/home/post-capture-tab/post-capture-details/post-capture-details.page.html
src/app/features/home/post-capture-tab/post-capture-details/post-capture-details.page.ts

See [the discussion on Slack](https://dt42-numbers.slack.com/archives/CS29L7Z5H/p1615445692068900).

Display username instead of email on PostCaptureDetailsPage.

---

src/app/features/home/home.page.html

Swap the order of PostCapture and Capture tab

---

src/app/features/home/capture-tab/capture-details/capture-details.page.ts
src/app/features/home/capture-tab/capture-tab.component.ts
src/app/features/home/home.page.html
src/app/features/home/home.page.scss
src/app/features/home/home.page.ts

- Implement store button on tab navbar.
- Open store with in-app browser.
- Apply better validation on geolocation icons.

Open store with in-app browser

---

src/app/features/home/home.page.ts
src/app/shared/services/dia-backend/transaction/dia-backend-transaction-repository.service.ts
src/app/shared/services/migration/migration.service.ts
src/app/shared/services/onboarding/onboarding.service.ts

Avoid fetching expired PostCaptures created before onboarding timestamp

---

src/app/app-routing.module.ts
src/app/features/contacts/contacts-routing.module.ts
src/app/features/contacts/contacts.module.ts
src/app/features/contacts/contacts.page.html
src/app/features/contacts/contacts.page.spec.ts
src/app/features/contacts/contacts.page.ts
src/app/features/home/home.page.html
src/app/shared/services/dia-backend/contact/dia-backend-contact-repository.service.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

Feature contact page

---

package-lock.json
package.json
src/app/app-routing.module.ts
src/app/features/home/capture-tab/capture-details/capture-details.page.html
src/app/features/home/post-capture-tab/post-capture-details/post-capture-details.page.html
src/app/shared/core/image-viewer/image-viewer-routing.module.ts
src/app/shared/core/image-viewer/image-viewer.module.ts
src/app/shared/core/image-viewer/image-viewer.page.html
src/app/shared/core/image-viewer/image-viewer.page.scss
src/app/shared/core/image-viewer/image-viewer.page.spec.ts
src/app/shared/core/image-viewer/image-viewer.page.ts

Implement fullscreen image viewer

---

src/app/app.component.ts
src/app/features/home/post-capture-tab/post-capture-tab.component.html
src/app/features/home/post-capture-tab/post-capture-tab.component.scss
src/app/features/home/post-capture-tab/post-capture-tab.component.ts
src/app/shared/services/network/network.service.ts

Show network status bar on PostCapture tab

---

src/app/app.module.ts
src/app/features/about/about.page.scss
src/app/features/contacts/contacts.page.html
src/app/features/contacts/contacts.page.scss
src/app/features/home/capture-tab/capture-details/capture-details.page.scss
src/app/features/home/capture-tab/capture-details/information/information.page.scss
src/app/features/home/capture-tab/capture-details/sending-post-capture/sending-post-capture.page.scss
src/app/features/home/inbox/inbox.page.scss
src/app/features/home/post-capture-tab/series/series.page.scss
src/app/features/home/transaction/transaction-details/transaction-details.page.scss
src/app/features/home/transaction/transaction.page.scss
src/app/features/privacy/privacy.page.scss
src/app/features/profile/profile.page.scss
src/app/features/settings/settings.page.scss

- Force Ionic style mode to be `md`.
- Make the text in `ion-title` to be centered.

Make contacts header style consistent with other headers

---

src/app/features/profile/profile.page.scss
src/app/shared/components/avatar/avatar.component.html
src/app/shared/components/avatar/avatar.component.ts

Show offline icon on avatar if no network connection.

Show offline icon on avatar.

---

src/app/features/home/post-capture-tab/series/series.page.ts

fix ui-release remove Unexpected  mockup image

---

src/app/features/about/about.page.ts
src/app/features/home/home-routing.module.ts
src/app/features/home/home.page.ts
src/app/features/home/onboarding/tutorial/tutorial.page.ts
src/app/shared/services/migration/migration.service.ts
src/app/shared/services/onboarding/onboarding.service.ts
src/app/shared/services/version/version.service.spec.ts
src/app/shared/services/version/version.service.ts

See [the discussion on Slack](https://dt42-numbers.slack.com/archives/C43K663U0/p1617947869039300).

Show tutorial for store/series release.

---

src/app/features/home/home.page.html
src/app/features/home/home.page.ts

See [the suggestion on Slack](https://dt42-numbers.slack.com/archives/CS29L7Z5H/p1617950529211300).

Change selectedIndex of home tabs to capture tab after capturing.

---

src/app/features/home/post-capture-tab/post-capture-details/post-capture-details.page.html
src/app/features/home/post-capture-tab/post-capture-details/post-capture-details.page.ts
src/app/features/home/post-capture-tab/series/series.page.html
src/app/shared/services/dia-backend/asset/dia-backend-asset-repository.service.ts
src/app/shared/services/dia-backend/series/dia-backend-series-repository.service.ts

See [the discussion on Slack](https://dt42-numbers.slack.com/archives/CS29L7Z5H/p1617948613203000).

Show PostCapture details on series view.

---

src/app/features/home/capture-tab/capture-details/contact-selection-dialog/contact-selection-dialog.component.ts
src/app/features/home/capture-tab/capture-details/contact-selection-dialog/friend-invitation-dialog/friend-invitation-dialog.component.ts
src/app/shared/services/android-back-button/android-back-button.service.spec.ts
src/app/shared/services/android-back-button/android-back-button.service.ts

See #636 and [the discussion on Slack](https://dt42-numbers.slack.com/archives/CS29L7Z5H/p1619062217270000).
Tested on Exodus 1.

Handle Android back button on a dialog opened.

---

src/app/features/home/capture-tab/capture-details/capture-details.page.ts
src/app/features/home/capture-tab/capture-details/options-menu/options-menu.component.html
src/app/features/home/capture-tab/capture-details/options-menu/options-menu.component.ts
src/app/features/home/post-capture-tab/post-capture-details/post-capture-details.page.html
src/app/features/home/post-capture-tab/post-capture-details/post-capture-details.page.scss
src/app/features/home/post-capture-tab/post-capture-details/post-capture-details.page.ts
src/app/features/home/post-capture-tab/post-capture-tab.component.ts
src/app/shared/services/dia-backend/asset/dia-backend-asset-repository.service.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

See [the discussion on Slack](https://dt42-numbers.slack.com/archives/C43K663U0/p1619206600151600). Tested on Brave browser, Chrome browser and Exodus 1.

View Supporting video on IPFS.

---

src/app/features/home/post-capture-tab/post-capture-details/post-capture-details.page.ts
src/app/shared/dia-backend/asset/dia-backend-asset-repository.service.ts

See #532. Tested on Exodus 1 and Brave.

Implement PostCapture deletion.

---

ios/App/App/AppDelegate.swift

Replace deprecated FirebaseInstanceID with FirebaseMessaging token

---

src/app/features/home/details/details.page.html
src/app/features/home/details/details.page.scss
src/app/features/home/details/details.page.ts

See [discussion on the Slack channel](https://dt42-numbers.slack.com/archives/CS29L7Z5H/p1621504949054400).

Fix details page toolbar oversize on iOS devices.

---

ios/App/App/Info.plist

fix ios Screen Rotation

---

src/app/features/home/inbox/inbox.page.scss
src/app/features/profile/profile.page.html
src/app/features/profile/profile.page.scss
src/global.scss

fix dark mode Insufficient color contrast

---

src/app/features/home/details/details.page.scss
src/app/features/home/onboarding/tutorial/tutorial.page.scss
src/global.scss

fix color display in any theme

---

src/app/shared/collector/collector.service.ts
src/app/shared/collector/signature/web-crypto-api-signature-provider/web-crypto-api-signature-provider.service.spec.ts
src/app/shared/repositories/proof/proof.spec.ts
src/app/shared/repositories/proof/proof.ts

Use sha256sum instead of file content base64 as object key in signed message.

Feature fix long video crash

---

src/app/features/home/details/details.page.ts
src/app/features/home/home.page.ts

Please check that whether I misused the RxJS operators, it's my first time using them.

Send user's auth token along with URL when opening Capture Club from App

---

src/app/features/home/transaction/transaction-details/transaction-details.page.scss
src/app/features/home/transaction/transaction-details/transaction-details.page.ts
src/app/features/home/transaction/transaction.page.scss
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

- Change displayed text for accepted state from "Accepted" to "Received"
- Change enum type from `Status.Accepted: 'accepted'` to `Status.Received: 'received'`

Change transaction state text from 'Accepted' to 'Received'

---

src/app/features/profile/email-verification/email-verification-routing.module.ts
src/app/features/profile/email-verification/email-verification.module.ts
src/app/features/profile/email-verification/email-verification.page.html
src/app/features/profile/email-verification/email-verification.page.scss
src/app/features/profile/email-verification/email-verification.page.spec.ts
src/app/features/profile/email-verification/email-verification.page.ts
src/app/features/profile/phone-verification/phone-verification-routing.module.ts
src/app/features/profile/phone-verification/phone-verification.module.ts
src/app/features/profile/phone-verification/phone-verification.page.html
src/app/features/profile/phone-verification/phone-verification.page.scss
src/app/features/profile/phone-verification/phone-verification.page.spec.ts
src/app/features/profile/phone-verification/phone-verification.page.ts
src/app/features/profile/profile-routing.module.ts
src/app/features/profile/profile.page.html
src/app/features/profile/profile.page.scss
src/app/features/profile/profile.page.ts
src/app/shared/dia-backend/auth/dia-backend-auth.service.ts
src/app/utils/validation.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

- Fix minor translation issue in figma
- For email verification, it currently sends account activation link instead of verification code
- If phone verification code is verified successfully, the verification page will be closed automatically after 3 seconds

Implement phone verification and email verification features

---

src/app/features/home/onboarding/prefetching-dialog/prefetching-dialog.component.ts
src/app/shared/collector/collector.service.ts
src/app/shared/collector/signature/web-crypto-api-signature-provider/web-crypto-api-signature-provider.service.spec.ts
src/app/shared/dia-backend/asset/dia-backend-asset-repository.service.ts
src/app/shared/dia-backend/asset/downloading/dia-backend-downloading.service.ts
src/app/shared/migration/service/migration.service.ts
src/app/shared/repositories/proof/proof.spec.ts
src/app/shared/repositories/proof/proof.ts

- Generate and save signature as discussed in #779 
- Trigger updating new signature and signed metadata to DIA backend on these conditions:
- Upgrading from 0.35.0 or lower version
- After pre-fetch is completed

Feature signed message

---

android/app/src/main/java/io/numbersprotocol/capturelite/MainActivity.java
src/app/features/home/post-capture-tab/post-capture-tab.component.scss
src/app/features/login/login.page.scss
src/app/features/signup/signup.page.scss

- Apply [this workaround](https://github.com/ionic-team/capacitor/discussions/1978#discussioncomment-708439) to force activating dark mode on Android.
- Fix buttons display issue in login page and signup page

Feature dark mode android workaround

---

src/app/features/home/details/details.page.html

#838 
- Tested on dev site (API v2)

Enable pruchased items to be sent as post-captures

---

src/app/features/home/onboarding/tutorial/tutorial.page.scss
src/app/features/home/post-capture-tab/series/series.page.scss
src/app/features/home/sending-post-capture/sending-post-capture.page.scss
src/app/shared/contact-selection-dialog/contact-selection-dialog.component.scss
src/global.scss

Overview
- Fix android dark mode issue for series page, send-post-capture page

Feature fix android dark mode issue

---

src/app/features/home/details/details.page.html
src/app/features/home/details/details.page.ts
src/app/shared/dia-backend/asset/dia-backend-asset-repository.service.ts
src/app/shared/dia-backend/auth/dia-backend-auth.service.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

#884 
Overview
- Can use "send" button to either "Copy IPFS link link" or "Share C2PA photo"
- For options menu
- Rename "Transfer capture" to "Transfer ownership"
- Add "mint NFT" button

Feature update view capture page

---

src/app/features/signup/signup.page.html
src/app/features/signup/signup.page.scss
src/app/shared/migration/service/migration.service.ts

- Skip migration if there is no previous version (i.e. when the APP is installed and logged in at the first time)
- Fix Capture logo display in signup page

Feature fix v3 migration issue

---

android/variables.gradle
src/app/features/home/details/actions/actions.page.html
src/app/features/home/details/actions/actions.page.ts
src/app/shared/actions/actions.service.ts

- Update field name in actions service to meet new Bubble DB schema
- Update Android target version to 30

Feature update for new bubble action schema

---

src/app/features/home/details/details.page.html
src/app/features/home/details/details.page.ts
src/app/features/home/details/information/session/information-session.service.ts
src/app/shared/dia-backend/asset/dia-backend-asset-repository.service.ts
src/app/shared/dia-backend/workflow/dia-backend-workflow.service.spec.ts
src/app/shared/dia-backend/workflow/dia-backend-workflow.service.ts

#987 
- Add `diaBackendWorkflowService` to retrieve workflow status (`getWorkflowById`)
- Do not show Capture options button when the post-creation workflow is not completed

Feature dont show options when uploading isnt complete

---

src/app/features/home/details/details.page.html
src/app/features/home/details/details.page.ts
src/app/features/home/details/information/session/information-session.service.ts

- Hide options that need backend workflow to complete, instead of hiding the whole menu

change(details.page): hide specific options instead of the whole menu

---

src/app/features/profile/profile.page.html
src/app/features/profile/profile.page.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

- Show warnings when user copies their private key

feat(profile.page): show warnings when copying private key

---

src/app/features/home/details/details.page.html
src/app/features/home/details/details.page.ts
src/app/features/home/details/information/session/information-session.service.ts
src/app/shared/actions/actions-dialog/actions-dialog.component.html
src/app/shared/dia-backend/asset/dia-backend-asset-repository.service.ts

- When there's no caption, will still display the icon and the text "No Caption"
- Can edit caption by clicking the caption text
Known issue:
- After editing, the displayed caption will not be updated immediately (need to re-enter the page). But currently don't know how to solve this efficiently

Feature can add caption

---

CHANGELOG.md
android/app/build.gradle
package-lock.json
package.json

Bump version to 0.49.0

---

CHANGELOG.md
android/app/build.gradle
package-lock.json
package.json

build: bump version to 0.49.1

---

CHANGELOG.md
android/app/build.gradle
package-lock.json
package.json

build: bump version to 0.50.0

---

CHANGELOG.md
android/app/build.gradle
package-lock.json
package.json

build: bump version to 0.50.1

---

CHANGELOG.md
android/app/build.gradle
package-lock.json
package.json

build: bump version to 0.51.0

---

CHANGELOG.md
android/app/build.gradle
package-lock.json
package.json

build: bump version to 0.51.1

---

.github/workflows/pre-release.yml
CHANGELOG.md
android/app/build.gradle
package-lock.json
package.json
src/app/features/home/details/actions/actions.page.ts

Bump version to 0.51.1

---

README.md

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202055733607470) by [Unito](https://www.unito.io)

Re-run failed job when deploy-app-store error

---

CHANGELOG.md
android/app/build.gradle
package-lock.json
package.json

Bump version to 0.54.0
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202087658337203) by [Unito](https://www.unito.io)

build: bump version to 0.54.0

---

CHANGELOG.md

Update CHANGELOG.md. Add Go pro/multi select file upload to 0.53.0.
See https://github.com/numbersprotocol/capture-lite/pull/1368#issuecomment-1091231163

update CHANGELOG.md. Add Go pro/multi select file upload to 0.53.0

---

src/app/features/home/capture-tab/capture-tab.component.ts
src/app/features/home/details/information/session/information-session.service.ts
src/app/shared/dia-backend/asset/dia-backend-asset-repository.service.ts
src/app/shared/dia-backend/asset/downloading/dia-backend-downloading.service.ts
src/app/shared/dia-backend/asset/refreshing/dia-backend-asset-refreshing.service.ts

Reverts numbersprotocol/capture-lite#1467
See https://dt42-numbers.slack.com/archives/CS29L7Z5H/p1649328985828869

Revert "Feature download asset using cdn"

---

CHANGELOG.md
android/app/build.gradle
package-lock.json
package.json

Build bump to 0.54.1

---

src/app/features/home/details/details.page.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

for https://app.asana.com/0/1201034543237057/1201939388393240/f
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202077213622495) by [Unito](https://www.unito.io)

Feature change ipfs url

---

package-lock.json
package.json
src/app/features/home/home.page.ts
src/app/features/settings/go-pro/go-pro-media-list-on-camera/go-pro-media-list-on-camera.component.html
src/app/features/settings/go-pro/go-pro-media-list-on-camera/go-pro-media-list-on-camera.component.ts
src/app/features/settings/go-pro/services/go-pro-bluetooth.service.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202100030337662) by [Unito](https://www.unito.io)

Feature try 2 fix go pro bluetooth connections

---

android/app/build.gradle
android/app/capacitor.build.gradle
android/app/src/main/assets/capacitor.plugins.json
android/capacitor.settings.gradle
ios/App/Podfile
package-lock.json
package.json
src/app/features/home/home.page.ts
src/app/features/settings/go-pro/go-pro-media-item-detail-on-camera/go-pro-media-item-detail-on-camera.component.html
src/app/features/settings/go-pro/go-pro-media-item-detail-on-camera/go-pro-media-item-detail-on-camera.component.scss
src/app/features/settings/go-pro/go-pro-media-item-detail-on-camera/go-pro-media-item-detail-on-camera.component.ts
src/app/features/settings/go-pro/go-pro-media-list-on-camera/go-pro-media-list-on-camera.component.html
src/app/features/settings/go-pro/go-pro-media-list-on-camera/go-pro-media-list-on-camera.component.ts
src/app/features/settings/go-pro/go-pro-media-viewer-with-native-player/go-pro-media-viewer-with-native-player.component.html
src/app/features/settings/go-pro/go-pro-media-viewer-with-native-player/go-pro-media-viewer-with-native-player.component.scss
src/app/features/settings/go-pro/go-pro-media-viewer-with-native-player/go-pro-media-viewer-with-native-player.component.spec.ts
src/app/features/settings/go-pro/go-pro-media-viewer-with-native-player/go-pro-media-viewer-with-native-player.component.ts
src/app/features/settings/go-pro/go-pro-routing.module.ts
src/app/features/settings/go-pro/go-pro.module.ts
src/app/features/settings/go-pro/services/go-pro-bluetooth.service.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202099946406067) by [Unito](https://www.unito.io)

Feature try 2 play go pro videos with native players

---

android/app/capacitor.build.gradle
android/app/src/main/assets/capacitor.plugins.json
android/capacitor.settings.gradle
android/variables.gradle
ios/App/Podfile
package-lock.json
package.json
src/app/features/home/custom-camera/custom-camera-routing.module.ts
src/app/features/home/custom-camera/custom-camera.module.ts
src/app/features/home/custom-camera/custom-camera.page.html
src/app/features/home/custom-camera/custom-camera.page.scss
src/app/features/home/custom-camera/custom-camera.page.spec.ts
src/app/features/home/custom-camera/custom-camera.page.ts
src/app/features/home/custom-camera/custom-camera.service.spec.ts
src/app/features/home/custom-camera/custom-camera.service.ts
src/app/features/home/custom-camera/custom-camera.ts
src/app/features/home/home-routing.module.ts
src/app/features/home/home.page.html
src/app/features/home/home.page.ts
src/app/features/settings/go-pro/go-pro-media-viewer-with-native-player/go-pro-media-viewer-with-native-player.component.spec.ts
src/global.scss

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202125276398306) by [Unito](https://www.unito.io)

Feature custom camera ux

---

src/app/features/wallets/wallets.page.html

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202142093633603) by [Unito](https://www.unito.io)

fix(wallets.page.html): temporarily hide buy NUM button

---

CHANGELOG.md
android/app/build.gradle
package-lock.json
package.json
src/app/features/settings/go-pro/go-pro-media-viewer-with-native-player/go-pro-media-viewer-with-native-player.component.ts
src/app/features/wallets/wallets.page.html

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202167223863353) by [Unito](https://www.unito.io)

Build bump to 0.55.0

---

package-lock.json

I just updated package-lock.json to use latest commit from [numbersprotocol/preview-camera](https://github.com/numbersprotocol/preview-camera) pluign.
main fix is in [numbersprotocol/preview-camera](https://github.com/numbersprotocol/preview-camera) repo
* [fix auto rotation in android](https://github.com/numbersprotocol/preview-camera/commit/bf3dd6a435881aa7d11f5d834129b61fa1a4548c)
* [fix auto rotation in ios](https://github.com/numbersprotocol/preview-camera/commit/70704ddd2b9d97ec1f916bb0016e1cdd32dc972e)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202233541368730) by [Unito](https://www.unito.io)

install preview-camera plugin with auto rotate feature

---

src/global.scss

fix(global.scss): default color for iOS safe areas

---

src/global.scss

@shc261392 I had an issue mergind dev to master at this pull-request https://github.com/numbersprotocol/capture-lite/pull/1609
Because there was one pull request that I merged directly to master (My mistake I sometimes forget to change pull request merge to develop branch)
So to fix that mistake I created [merge-latest-branch-from-master-to-develop](https://github.com/numbersprotocol/capture-lite/tree/merge-latest-branch-from-master-to-develop) now I need to again merge this branch to develop then to master.
Sorry, next time I will make sure all my pull requests go to develop first

Merge latest branch from master to develop

---

CHANGELOG.md
android/app/build.gradle
package-lock.json
package.json
src/app/features/invitation/invitation.page.scss

I forgot to center app bar text so 
* I centered app bar text as shown in screenshot
* Bumped app version 
Because it's a simple change I decided to do in 1 pull request :sweat_smile:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202270275042402) by [Unito](https://www.unito.io)

Build bump 0.56.2

---

src/app/features/home/details/details.page.ts
src/app/shared/dia-backend/asset/dia-backend-asset-repository.service.ts
src/app/utils/url.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202299910955335) by [Unito](https://www.unito.io)

open sertificate with temporary token

---

src/app/features/home/details/details.page.ts
src/app/features/home/home.page.ts
src/app/features/settings/user-guide/user-guide.page.html
src/app/features/settings/user-guide/user-guide.page.ts
src/app/shared/user-guide/user-guide.service.ts

Show user guide based on platform
- on iOS show an old user guide (aka slide)
- on Android, Web show a new user guide

Fix temporarely disable in app user guide

---

src/app/shared/share/share.service.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202277524142637) by [Unito](https://www.unito.io)

fix: inivtation share referral code text

---

src/app/features/settings/user-guide/user-guide.page.html
src/app/features/settings/user-guide/user-guide.page.ts
src/app/shared/user-guide/user-guide.service.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202345478442927) by [Unito](https://www.unito.io)

fix(user-guide): highligh first capture once and don't show again

---

CHANGELOG.md
android/app/build.gradle
package-lock.json
package.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202353729734243) by [Unito](https://www.unito.io)

build: bump to 0.57.3

---

CHANGELOG.md
android/app/build.gradle
package-lock.json
package.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202368652669268) by [Unito](https://www.unito.io)

Build bump 0.58.0

---

src/app/features/home/details/details.page.ts
src/app/shared/share/share.service.ts
src/app/utils/url.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202400006790927) by [Unito](https://www.unito.io)

Fix-revert-share-asset-profile-url

---

src/app/features/home/details/details.page.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202462645744793) by [Unito](https://www.unito.io)

Fix show catpure actions regardless of backend response

---

src/app/features/profile/phone-verification/phone-verification.page.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202421416003563) by [Unito](https://www.unito.io)

fix(phone-verification.page): specify error messages on phone submit

---

CHANGELOG.md
android/app/build.gradle
ios/App/App/Info.plist
package-lock.json
package.json
src/app/app.component.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202518999380053) by [Unito](https://www.unito.io)

Fix temporarely disable apps flyer at app launch

---

src/app/features/profile/phone-verification/phone-verification.page.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202549939083324) by [Unito](https://www.unito.io)

fix(phone-verification): show proper msg for duplicate phones

---

src/app/features/home/details/details.page.ts
src/app/shared/actions/service/actions.service.ts

Because it's also part of 0.61.0 release

send generate SEO img & description on share asset

---

src/app/features/home/custom-camera/custom-camera.page.ts
src/app/features/home/custom-camera/custom-camera.service.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202628023786015) by [Unito](https://www.unito.io)

fix(custom-camera): make sure confirm button works properly

---

src/app/shared/share/share.service.ts
src/app/utils/constants.ts
src/app/utils/url.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202670578315346) by [Unito](https://www.unito.io)

fix: change app download url

---

src/app/features/home/explore-tab/explore-tab/explore-tab.component.html
src/app/features/home/explore-tab/explore-tab/explore-tab.component.scss
src/app/features/home/explore-tab/explore-tab/explore-tab.component.spec.ts
src/app/features/home/explore-tab/explore-tab/explore-tab.component.ts
src/app/features/home/home.module.ts
src/app/features/home/home.page.html

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202678121650522) by [Unito](https://www.unito.io)

Feature rebrand home page clean pr

---

src/app/features/home/home.page.ts
src/app/shared/user-guide/user-guide.service.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202712901521499) by [Unito](https://www.unito.io)

feat(user-guide): temporarely disable user guide

---

src/app/features/home/explore-tab/explore-tab/explore-tab.component.html
src/app/features/home/explore-tab/explore-tab/explore-tab.component.ts
src/app/shared/pipes/safe-resource-url/safe-resource-url.pipe.spec.ts
src/app/shared/pipes/safe-resource-url/safe-resource-url.pipe.ts
src/app/shared/shared.module.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202712934313372) by [Unito](https://www.unito.io)

fix(explore-tab): pass iframe url with user token

---

src/app/features/home/home.page.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202737063803477) by [Unito](https://www.unito.io)

fix(home.page): use custom camera on native platforms

---

android/app/src/main/res/xml/network_security_config.xml

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202765852774242) by [Unito](https://www.unito.io)

fix(details.page): include iframe url to trusted domains on Android

---

src/app/features/home/details/details.page.html

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202737111552072) by [Unito](https://www.unito.io)

fix(details.page): temporarily hide donate button

---

src/app/features/home/explore-tab/explore-tab/explore-tab.component.scss

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202737111706016) by [Unito](https://www.unito.io)

fix(explore.tab): iframe height

---

ios/App/App/Info.plist

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202765748989243) by [Unito](https://www.unito.io)

fix ios status bar color, set to white

---

README.md

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202802524884900) by [Unito](https://www.unito.io)

change(README.md): add necessary env keys to build the app

---

src/app/features/home/home.page.html
src/app/features/home/home.page.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202846211873563) by [Unito](https://www.unito.io)

feat(home.page): refresh explore tab if clicked twice

---

src/app/features/home/explore-tab/explore-tab/explore-tab.component.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202846242800227) by [Unito](https://www.unito.io)

change(explore-tab): iframe url to version-qa

---

src/app/features/home/details/details.page.ts

Feature changes
1. update (wrong) pid to nid
2. remove `iframeLoadedFrom=CaptureApp`
3. add `from=mycapture`
Signed-off-by: Bofu Chen (bafu) <bofu@numbersprotocol.io>

Feature: Update asset_page URL params

---

package-lock.json
src/app/features/home/custom-camera/custom-camera.page.html
src/app/features/home/custom-camera/custom-camera.page.ts
src/app/features/home/custom-camera/custom-camera.service.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202901800685234) by [Unito](https://www.unito.io)

Feat tap to focus

---

src/app/features/home/details/details.page.ts
src/app/shared/share/share.service.ts
src/app/utils/url.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202898825213478) by [Unito](https://www.unito.io)

Feature use NSE instead of Authmedia

---

src/app/features/home/details/details.page.html
src/app/features/home/details/details.page.ts
src/app/features/home/explore-tab/explore-tab/explore-tab.component.html
src/app/features/home/explore-tab/explore-tab/explore-tab.component.ts
src/app/shared/dia-backend/auth/dia-backend-auth.service.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202928577003526) by [Unito](https://www.unito.io)

Feature pass new jwt to iframe

---

package-lock.json
src/app/features/home/custom-camera/custom-camera.page.html
src/app/features/home/custom-camera/custom-camera.page.scss
src/app/features/home/custom-camera/custom-camera.page.ts
src/app/features/home/custom-camera/custom-camera.service.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202965338898968) by [Unito](https://www.unito.io)

Feature zoom in out

---

ios/App/App.xcodeproj/project.pbxproj

bump iOS deployment target to 14.7 via Xcode
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203020918062298) by [Unito](https://www.unito.io)

bump iOS deployement target to 14.7

---

android/app/src/main/res/drawable/ic_capture_lite.xml

To code reviewer.
This commit changes the SVG content of the notification icon (Android only).
Here is the [demo](https://i.imgur.com/EMSLQPL.mp4).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203042222871777) by [Unito](https://www.unito.io)

fix update android notification icon

---

ios/App/Configuration.storekit
src/app/shared/dia-backend/num/dia-backend-num.service.ts

Fetch num point price list from new URL provided by Ethan
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203042342275297) by [Unito](https://www.unito.io)

Feat update num price list endpoint

---

src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202992865722678) by [Unito](https://www.unito.io)

change onboarding text to final version

---

src/app/features/login/login.page.html
src/app/features/login/login.page.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

Just fix the typo "Forget Password" to "Forgot Password".
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203054497289588) by [Unito](https://www.unito.io)

fix(login-page): typo forget password

---

package-lock.json
src/app/features/home/custom-camera/custom-camera.page.html
src/app/features/home/custom-camera/custom-camera.page.scss
src/app/features/home/custom-camera/custom-camera.page.ts
src/app/features/home/custom-camera/custom-camera.service.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

Add feature to select camera quality to use Max quality and Social quality (IG post size 1980x1080). Here is the [claap](https://app.claap.io/numbers-protocol/devs-only-max-social-size-ios-android-c-O35CsUM4Uy-cP_tMyzaSNow) with a demo for a better explanation.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203097683475948) by [Unito](https://www.unito.io)

Feature custom camera low high quality selection

---

src/app/features/home/capture-tab/capture-tab.component.html
src/app/features/home/capture-tab/capture-tab.component.scss
src/app/features/home/capture-tab/capture-tab.component.ts
src/app/features/home/home.page.html

This PR is for pseudo-lazy loading, here is the [claap](https://app.claap.io/numbers-protocol/devs-pseudo-lazy-loading-assets-c-O35CsUM4Uy-gXBdUPxOoT4r) demo.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203207096119735) by [Unito](https://www.unito.io)

feat(capture-tab): implement pseudo lazy loading

---

ios/App/App.xcodeproj/project.pbxproj

Fix iOS build
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203276378419599) by [Unito](https://www.unito.io)

change ios Provisioning profile to NumbersAppDistributionV4

---

src/app/features/wallets/buy-num/buy-num.page.html
src/app/features/wallets/buy-num/buy-num.page.ts
src/app/features/wallets/wallets.page.html
src/app/shared/in-app-store/in-app-store.service.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

**NOTE: Should be included in the v221101 release.**
Basically change text from Points to Credits in Wallets page, related asana [task](https://app.asana.com/0/1201016280880500/1203148169877398/f)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203276760311493) by [Unito](https://www.unito.io)

Feature change text from buy points to buy credits clean commits

---

src/app/features/home/details/actions/actions.page.ts
src/app/features/home/details/details.page.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

**Part of v221108-capture-app-ionic release note**
Just chagne tranlstaion from "CaptureClub" to "Capture App"
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203299459347389) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201016280880500/1203299459347389

fix(translation): change capture club to capture app

---

src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

**Part of v221108-capture-app-ionic release note**
Fix translation for Can not perform Mint & share action.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203320784662267) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201016280880500/1203320784662267

fix(translations): canNotPerformMintAndShareAction

---

src/app/features/home/explore-tab/explore-tab/explore-tab.component.html
src/app/features/home/explore-tab/explore-tab/explore-tab.component.ts
src/app/features/home/home.page.ts
src/app/shared/iframe/iframe.service.spec.ts
src/app/shared/iframe/iframe.service.ts
src/app/shared/shared.module.ts

**Part of v221108-capture-app-ionic release note**
Here is the reload explore tab UX [before](https://i.imgur.com/gafQtkI.mp4) and [after](https://i.imgur.com/ER1yXWD.mp4).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203327160702787) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201016280880500/1203327160702787

fix(explore-tab): reload only iframe

---

src/app/features/home/details/details.page.ts

**Part of v221115-capture-app-ionic release**
Temporarely remove Mint & Share option from options menu in Details page.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203361296670832) by [Unito](https://www.unito.io)

fix(details.page): Temporarely remove Mint & Share button

---

src/app/features/home/details/details-routing.module.ts
src/app/features/home/details/details.page.ts
src/app/features/home/details/edit-caption/edit-caption-routing.module.ts
src/app/features/home/details/edit-caption/edit-caption.module.ts
src/app/features/home/details/edit-caption/edit-caption.page.html
src/app/features/home/details/edit-caption/edit-caption.page.scss
src/app/features/home/details/edit-caption/edit-caption.page.spec.ts
src/app/features/home/details/edit-caption/edit-caption.page.ts
src/app/shared/iframe/iframe.service.spec.ts
src/app/shared/iframe/iframe.service.ts

**Part of v221115-capture-app-ionic release**
[claap](https://app.claap.io/numbers-protocol/dev-qa-ionic-finish-update-caption-c-O35CsUM4Uy-Xyjkj5lw7UHt) explanation. Note: to test locally use **/version-v221115/** of capture iframe
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203361251433630) by [Unito](https://www.unito.io)

Feat edit caption via iframe

---

package-lock.json
package.json

The fix was straight forward just installed the missing package. Although it's a bit strange in normal angular projects we don't see this package much.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203561193507624) by [Unito](https://www.unito.io)

fix: github CI lint

---

src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

fix for https://github.com/numbersprotocol/capture-lite/issues/2338
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203478922319669) by [Unito](https://www.unito.io)

fix: translation for custom camera next button

---

android/app/src/main/assets/capacitor.config.json
ios/App/App/capacitor.config.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203486465100300) by [Unito](https://www.unito.io)

add missing files generated after `npx cap sync`

---

package-lock.json
package.json
src/app/features/home/custom-camera/custom-camera.page.html
src/app/features/home/custom-camera/custom-camera.page.scss
src/app/features/home/custom-camera/custom-camera.page.ts

Here is the [claap](https://app.claap.io/numbers-protocol/camera-orientation-fixed-i-os-android-c-O35CsUM4Uy-mstGyM9XZyme) of this PR.
Regarding [a0bdb23](https://github.com/numbersprotocol/capture-lite/pull/2401/commits/a0bdb232c9145b3bbce3905e06fc15a2e26a68c7) for some reason `HammerInput` is not recognized when I run **npm run test.ci** locally [(screenshot)](https://i.imgur.com/XywtVF0.png) but it's recognized **by VS Code during development** and **GitHub actions**.
I also tried to add configure tsconfig.json as suggested [here](https://github.com/angular/components/issues/1944#issuecomment-264702386) but it didn't work so I just use any as a parameter.
NOTE: this PR is not added to any release cards by QA yet. Once added I will update the summary accordingly.
┆Issue is synchronized …

Feat camera auto rotate

---

CHANGELOG.md
android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj
package-lock.json
package.json
src/app/features/home/custom-camera/custom-camera.page.scss

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203607082031603) by [Unito](https://www.unito.io)

Release 0.71.2

---

android/app/src/main/res/xml/network_security_config.xml

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203599350219268) by [Unito](https://www.unito.io)

remove captureappiframe.numbersprotocol.io from clear traffic

---

src/app/features/home/capture-tab/capture-tab.component.html

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203616978931426) by [Unito](https://www.unito.io)

feat(capture-tab): allow user to update username

---

src/app/features/wallets/transfer/transfer.page.html
src/app/features/wallets/transfer/transfer.page.ts
src/app/features/wallets/wallets.page.html
src/app/features/wallets/wallets.page.scss
src/app/features/wallets/wallets.page.ts
src/app/shared/dia-backend/wallet/dia-backend-wallet.service.ts
src/app/shared/order-detail-dialog/order-detail-dialog.component.html
src/app/shared/order-detail-dialog/order-detail-dialog.component.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

This PR is not finished yet but has main refactor commits.
Once I get the translation and other materials I will continue commits in this PR.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203616961007168) by [Unito](https://www.unito.io)

Feat wallet page use mainnet num

---

src/app/features/home/capture-tab/capture-tab.component.html
src/app/features/wallets/transfer/transfer.page.html
src/app/shared/order-detail-dialog/order-detail-dialog.component.html

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203621076209232) by [Unito](https://www.unito.io)

fix: linting in html files

---

src/app/features/wallets/wallets.page.html

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203621612257879) by [Unito](https://www.unito.io)

fix(wallet.page): text MAINNET to Mainnet

---

CHANGELOG.md
android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj
package-lock.json
package.json
src/app/features/wallets/transfer/transfer.page.scss
src/app/features/wallets/wallets.page.scss

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203646197838113) by [Unito](https://www.unito.io)

Release 0.72.2

---

android/app/src/main/java/io/numbersprotocol/capturelite/MainActivity.java

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203655259332063) by [Unito](https://www.unito.io)

change: disable force webview darkmode on android

---

src/app/features/wallets/transfer/transfer.page.scss

This reverts commit 0445cf0425cc1eeaa3e0a1869c6f577c48e238d7.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203660811277231) by [Unito](https://www.unito.io)

Revert "fix(transfer.page): change qr code text color to white"

---

CHANGELOG.md
android/app/build.gradle
android/app/src/main/java/io/numbersprotocol/capturelite/MainActivity.java
ios/App/App.xcodeproj/project.pbxproj
package-lock.json
package.json
src/app/features/wallets/transfer/transfer.page.scss

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203662291904206) by [Unito](https://www.unito.io)

Release 0.72.3

---

src/app/features/wallets/transfer/transfer.page.scss

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203672902353605) by [Unito](https://www.unito.io)

fix(transfer.page): set QR code text to white

---

src/app/app-routing.module.ts
src/app/features/contacts/contacts.page.html
src/app/features/data-policy/data-policy-routing.module.ts
src/app/features/data-policy/data-policy.module.ts
src/app/features/data-policy/data-policy.page.html
src/app/features/data-policy/data-policy.page.scss
src/app/features/data-policy/data-policy.page.spec.ts
src/app/features/data-policy/data-policy.page.ts
src/app/features/home/home.page.html
src/app/features/home/home.page.scss
src/app/features/home/home.page.ts
src/app/features/terms-of-use/terms-of-use-routing.module.ts
src/app/features/terms-of-use/terms-of-use.module.ts
src/app/features/terms-of-use/terms-of-use.page.html
src/app/features/terms-of-use/terms-of-use.page.scss
src/app/features/terms-of-use/terms-of-use.page.spec.ts
src/app/features/terms-of-use/terms-of-use.page.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203781772835372) by [Unito](https://www.unito.io)

Feat v230112 rebranded app menu

---

src/app/features/home/custom-camera/custom-camera.page.html

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203850692358764) by [Unito](https://www.unito.io)

fix(custom-camera): focus on camera preview click

---

CHANGELOG.md
android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj
package-lock.json
package.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203855807817564) by [Unito](https://www.unito.io)

Milestone v230112

---

android/app/src/main/res/drawable/splash_centered.xml
android/app/src/main/res/values-v26/styles.xml

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203973897197487) by [Unito](https://www.unito.io)

fix: android 11 splash screen

---

CHANGELOG.md
android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj
package-lock.json
package.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203966671521672) by [Unito](https://www.unito.io)

Release 0.74.0

---

CHANGELOG.md
android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj
package-lock.json
package.json
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203984273377309) by [Unito](https://www.unito.io)

Hotfix adjust the text below the invite friends

---

CHANGELOG.md
android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj
ios/App/ExportOptions.plist
package-lock.json
package.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203984228802041) by [Unito](https://www.unito.io)

Hotfix v230209 ci for ios upload

---

src/app/features/home/details/details-iframe/details-iframe.component.html
src/app/features/home/details/details-iframe/details-iframe.component.scss
src/app/features/home/details/details-iframe/details-iframe.component.spec.ts
src/app/features/home/details/details-iframe/details-iframe.component.ts
src/app/features/home/details/details.module.ts
src/app/features/home/details/details.page.html
src/app/features/home/details/details.page.scss
src/app/features/home/details/details.page.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1204052246255147) by [Unito](https://www.unito.io)

fix(details.page): swipe left/right shows expected capture

---

src/app/app.component.ts
src/app/features/settings/settings.page.ts
src/app/features/wallets/wallets.page.ts
src/app/shared/actions/service/order-history.service.ts
src/app/shared/collector/signature/capture-app-web-crypto-api-signature-provider/capture-app-web-crypto-api-signature-provider.service.spec.ts
src/app/shared/collector/signature/capture-app-web-crypto-api-signature-provider/capture-app-web-crypto-api-signature-provider.service.ts
src/app/shared/migration/service/migration.service.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1204110943337771) by [Unito](https://www.unito.io)

Feat v230223 special provider for photos taken from capture app

---

src/app/features/home/capture-tab/capture-tab.component.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1204235727555206) by [Unito](https://www.unito.io)

feat: show clear error handling of change username

---

set-secret.js
src/app/features/settings/settings.page.ts
src/app/shared/dia-backend/auth/dia-backend-auth.service.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1204235627544639) by [Unito](https://www.unito.io)

feat: delete account for real

---

.github/workflows/pre-release.yml

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1204235485875681) by [Unito](https://www.unito.io)

fix(pre-release): build-ios-prod

---

src/app/shared/dia-backend/asset/uploading/dia-backend-asset-uploading.service.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1204235630604334) by [Unito](https://www.unito.io)

fix: show message if asset registration insufficient NUM

---

src/app/features/home/custom-camera/custom-camera.page.html
src/app/features/home/custom-camera/custom-camera.page.scss
src/app/features/home/custom-camera/custom-camera.page.ts
src/app/features/home/custom-camera/custom-camera.service.ts
src/app/shared/camera/camera.service.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1204235736179094) by [Unito](https://www.unito.io)

Feat v230310 sprint 2 upload image

---

.github/workflows/build-apks.yml
.github/workflows/pre-release.yml
set-secret.js
src/app/shared/dia-backend/auth/dia-backend-auth.service.ts

This PR will 
- add PIPEDREAM_DELETE_CAPTURE_ACCOUNT env var to pre-release, build-apks config files
- refactor related files that uses PIPEDREAM_DELETE_CAPTURE_ACCOUNT
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1204353862364776) by [Unito](https://www.unito.io)

Hotfix issue GitHub ci add missing pipedream url to pre release.yml & build apks.yml

---

src/app/features/home/custom-camera/custom-camera.page.ts
src/app/features/home/custom-camera/custom-camera.service.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1204422013357348) by [Unito](https://www.unito.io)

Hotfix v230310 issue only i os user could upload the duplicate photo

---

src/app/features/home/details/details-iframe/details-iframe.component.ts

Unexpected reloads happen during asset registration.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1204422015794957) by [Unito](https://www.unito.io)

fix(details-page): unexpected iframe reloads

---

.github/workflows/build-apks.yml
src/app/app.component.ts
src/app/shared/apps-flyer/apps-flyer.service.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1204430604757253) by [Unito](https://www.unito.io)

Feat v230321 capture app flavours should be built automatically by ci/cd

---

src/app/features/signup/signup.page.ts
src/app/shared/dia-backend/auth/dia-backend-auth.service.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1204430812544231) by [Unito](https://www.unito.io)

Feat v230321 set device information when user signing up

---

package-lock.json
package.json
src/app/features/home/custom-camera/custom-camera.page.ts
src/app/features/home/custom-camera/custom-camera.service.ts
src/app/features/settings/settings.page.html
src/app/features/settings/settings.page.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1204430731824590) by [Unito](https://www.unito.io)

Feature v230321 asset saved to device camera roll

---

src/app/features/home/custom-camera/pre-publish-mode/pre-publish-mode.component.ts

toggleCropFeature to isCropFeatureEnabled
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1204666118511813) by [Unito](https://www.unito.io)

Refactor v230413 pre publish component

---

.github/workflows/build-apks.yml
src/app/shared/apps-flyer/apps-flyer.service.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1204960164447812) by [Unito](https://www.unito.io)

Fix build apks ci cd

---

src/app/features/home/custom-camera/custom-camera.service.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1204923841830143) by [Unito](https://www.unito.io)

refactor(custom-camera.service): according to #discussion_r1144354340

---

src/app/features/home/capture-tab/capture-tab.component.html
src/app/features/home/capture-tab/capture-tab.component.ts
src/app/features/home/custom-camera/custom-camera.page.ts
src/app/shared/capture-tab/capture-tab.service.spec.ts
src/app/shared/capture-tab/capture-tab.service.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

Added new tab DRAFT. After user captures photo/video it will autonavigate to DRAFT tab as requested by QA.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1205122645082591) by [Unito](https://www.unito.io)

Feat v230711 add new tab draft on my capture tab

---

android/app/capacitor.build.gradle
android/app/src/main/assets/capacitor.plugins.json
android/capacitor.settings.gradle
ios/App/Podfile
ios/App/Podfile.lock
package-lock.json
package.json
src/app/shared/media/media-store/media-store.service.ts
src/app/utils/url.ts

reverts https://github.com/numbersprotocol/capture-lite/pull/2923
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1205150336949091) by [Unito](https://www.unito.io)

Revert thumbnail generation with native plugin

---

src/app/features/home/capture-tab/capture-tab.component.html
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1205151316032236) by [Unito](https://www.unito.io)

fix(capture-tab): change VALIDATED to VERIFIED

---

.github/workflows/build-apks.yml
.github/workflows/build.yml
.github/workflows/pre-release.yml

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1205152019967407) by [Unito](https://www.unito.io)

fix: github actions "build android" steps

---

android/app/src/main/AndroidManifest.xml
ios/App/Podfile.lock
package-lock.json
package.json
src/app/shared/apps-flyer/apps-flyer.service.ts

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1205155451686734) by [Unito](https://www.unito.io)

Fix v230725 appsflyer after capacitor 5 migration

---

src/app/features/settings/settings.page.ts

Fixes https://github.com/numbersprotocol/capture-lite/issues/2920. Here is the [demo](https://app.claap.io/numbers-protocol/issue-update-icon-to-reflect-completed-email-ver-c-O35CsUM4Uy-hFnJD1fCe2fa)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1205155180014826) by [Unito](https://www.unito.io)

fix(settings.page): sync profile after email verified

---

src/app/features/home/activities/activities.page.html
src/app/features/home/activities/activities.page.scss
src/app/features/home/activities/network-action-order-details/network-action-order-details.page.html
src/app/features/home/activities/network-action-order-details/network-action-order-details.page.scss
src/app/features/home/activities/network-action-order-details/network-action-order-details.page.ts
src/app/features/home/activities/network-action-orders/network-action-orders.component.html
src/app/features/home/activities/network-action-orders/network-action-orders.component.scss
src/app/features/home/activities/network-action-orders/network-action-orders.component.ts
src/app/shared/dia-backend/store/dia-backend-store.service.ts
src/app/shared/iframe/iframe.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

Closes https://github.com/numbersprotocol/capture-lite/issues/2658. Here is the [demo](https://app.claap.io/feat-v230725-showing-order-information-in-the-transaction-c-O35CsUM4Uy-Q4cwwujSE0SW)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1205155195069204) by [Unito](https://www.unito.io)

Feature v230725 showing order information in the transaction

---

ios/App/App.xcodeproj/project.pbxproj

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1205201447642496) by [Unito](https://www.unito.io)

feat(ios): set minimum deployement target to 15.6

---

src/app/features/home/activities/network-action-order-details/network-action-order-details.page.ts

Fixes [Comment by @Sam on [issue] Order detail page issues](https://app.asana.com/0/0/1205157942954425/1205221520279676/f).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1205221415631830) by [Unito](https://www.unito.io)

fix: iframe copy order id to clipboard

---

src/app/features/home/details/capture-details-with-iframe/capture-details-with-iframe.component.ts

Fixes https://github.com/numbersprotocol/capture-lite/issues/2900

fix: automatically navigate back on iOS 16 and higher

---

android/app/src/main/AndroidManifest.xml
ios/App/App/App.entitlements
src/app/app.component.ts

Implements https://github.com/numbersprotocol/capture-lite/issues/2835

Feature v230808 configure capture app to receive deep links

---

src/app/shared/share/share.service.ts
src/app/utils/constants.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

Fixes https://github.com/numbersprotocol/capture-lite/issues/2919

fix: change text for referral code invitation

---

src/app/features/home/details/details.page.ts
src/app/shared/dia-backend/asset/dia-backend-asset-repository.service.ts

Closes https://github.com/numbersprotocol/capture-lite/issues/2979
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1205375594661179) by [Unito](https://www.unito.io)

Fix v230814 issue some asset can't show "share asset profile" on asset page

---

ios/App/Podfile
ios/App/Podfile.lock
package-lock.json
package.json

closes https://github.com/numbersprotocol/capture-lite/issues/2954
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1205375852760128) by [Unito](https://www.unito.io)

Feature v230822 use appsflyer official plugin

---

src/app/features/home/activities/network-action-order-details/network-action-order-details.page.ts

fixes https://github.com/numbersprotocol/capture-lite/issues/3016
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1205517759520221) by [Unito](https://www.unito.io)

fix: order details iframe url

---

src/app/features/home/details/actions/action-details/action-details-routing.module.ts
src/app/features/home/details/actions/action-details/action-details.module.ts
src/app/features/home/details/actions/action-details/action-details.page.html
src/app/features/home/details/actions/action-details/action-details.page.scss
src/app/features/home/details/actions/action-details/action-details.page.spec.ts
src/app/features/home/details/actions/action-details/action-details.page.ts
src/app/features/home/details/actions/actions-routing.module.ts
src/app/features/home/details/actions/actions.page.html
src/app/features/home/details/actions/actions.page.scss
src/app/features/home/details/actions/actions.page.ts
src/app/features/home/details/actions/what-are-actions/what-are-actions-routing.module.ts
src/app/features/home/details/actions/what-are-actions/what-are-actions.module.ts
src/app/features/home/details/actions/what-are-actions/what-are-actions.page.html
src/app/features/home/details/actions/what-are-actions/what-are-actions.page.scss
src/app/features/home/details/actions/what-are-actions/what-are-actions.page.spec.ts
src/app/features/home/details/actions/what-are-actions/what-are-actions.page.ts
src/app/shared/order-detail-dialog/order-detail-dialog.component.html
src/app/shared/order-detail-dialog/order-detail-dialog.component.scss
src/app/shared/order-detail-dialog/order-detail-dialog.component.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json
src/global.scss

Implements [Network App UI update (part A)](https://app.asana.com/0/1201016280880500/1205359034159897/f). Here is the [demo](https://app.claap.io/numbers-protocol/v231003-capture-cam-ionic-c-O35CsUM4Uy-NMZTmP6JQ2J_) (visual representaion) of this PR
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1205841604382462) by [Unito](https://www.unito.io)

V231003 newtork app UI update

---

src/app/utils/url.ts

Fixes https://github.com/numbersprotocol/capture-lite/issues/3155
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1206262187947088) by [Unito](https://www.unito.io)

feat(urls.ts): redirect nftsearch.site to verify.numbersprotocol.io

---

src/app/features/home/capture-tab/capture-tab.component.ts

Fixes issue 1 from [huddle summary](https://app.asana.com/0/0/1206491967244628/1206551064456070/f). Here is the [demo](https://app.claap.io/numbers-protocol/fix-prevent-refresh-restore-during-uploads-c-O35CsUM4Uy-Y5OA181iHp_Z).

fix(capture-tab): prevent refresh/restore during upload

---

src/app/shared/dia-backend/service/dia-backend-service.service.ts

Implements https://github.com/numbersprotocol/capture-lite/issues/3229
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1206743878079688) by [Unito](https://www.unito.io)

feat: pass x-api-key to app-info API call

---

src/app/features/home/capture-tab/capture-tab.component.ts
src/app/shared/dia-backend/asset/dia-backend-asset-repository.service.ts
src/app/shared/dia-backend/asset/downloading/dia-backend-downloading.service.ts
src/app/shared/dia-backend/asset/uploading/dia-backend-asset-uploading.service.ts
src/app/shared/repositories/proof/proof.spec.ts
src/app/shared/repositories/proof/proof.ts

Implements https://github.com/numbersprotocol/capture-lite/issues/3138

Feature sort assets in verified tab by uploaded at

---

ios/App/App.xcodeproj/project.pbxproj
ios/App/ExportOptions.plist

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1206738363429915) by [Unito](https://www.unito.io)

change(iOS): Provisioning profile to NumbersAppDistributionV6

---

src/app/shared/actions/service/actions.service.ts

- Sort network actions by `index` field to allow control of display order

feat(ActionService): add query param sort_field=index to sort network actions

---

src/app/features/home/details/details.page.ts
src/assets/i18n/en-us.json
src/assets/i18n/zh-tw.json

1. Adjust the C2PA loading text and pass the current URL for returning back [#3248](https://github.com/numbersprotocol/capture-lite/pull/3248)
​
┆The issue is also created on [Asana](https://app.asana.com/0/1201016280880500/1207444301446207)

feat(features/home/details): adjust C2PA text

---

src/app/features/home/capture-tab/capture-tab.component.html
src/app/features/home/capture-tab/capture-tab.component.ts
src/app/shared/dia-backend/auth/dia-backend-auth.service.ts
src/app/shared/share/share.service.ts
src/app/utils/url.ts

1. Add a shared link to the Showcase page on the Home page [#3256](https://github.com/numbersprotocol/capture-lite/pull/3256)
​
┆The issue is also created on [Asana](https://app.asana.com/0/1201016280880500/1208645860977012)

feat(features/home): add showcase shared link

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/pre-release.yml
.github/workflows/test.yml

1. Fix issue preventing Dependabot checks from completing
​
┆The issue is also created on [Asana](https://app.asana.com/0/1201016280880500/1208745294553889)

chore(.github): fix dependabot checks

---

src/app/shared/migration/service/migration.service.ts

1. Fix the persistent migration popup dialog caused by incorrect string version comparison.
​
┆The issue is also created on [Asana](https://app.asana.com/0/1201016280880500/1209464046668971)

fix(shared/migration): persistent popup dialog

---

src/app/features/signup/signup.page.ts
src/app/shared/apps-flyer/apps-flyer.service.ts
src/app/shared/dia-backend/auth/dia-backend-auth.service.ts
src/app/shared/push-notification/push-notification.service.ts
src/app/shared/social-login-button/social-login-button.component.ts

Resolves #3331
Fix issue where login gets stuck on "Please wait…" after logout on Android or after rejecting a notification.

fix(shared): Google login issue on Android
