- src/app/pages/home/inbox/inbox.page.ts
- src/app/utils/storage/storage.ts
WORKAROUND: Catch error throw on deleting files.
Rationale (zh-tw)
app 使用的儲存方式是依靠 Capacitor 這個 lib 來幫我們處理不同平台的資料儲存。但是這個 lib 有不少問題與限制，舉例而言，在 Android 上它偶爾會刪不掉先前透過它儲存的檔案，然後回傳的錯誤訊息也很不明確。因為發送 PostCapture 之後要刪掉相關的檔案，然後 Capacitor 刪除過程發生錯誤，因此中斷了這個行為，而沒有自動跳回 Capture 頁面。目前最快的 workaround 是直接 catch 掉所有  Capacitor.Filesystem.deleteFile()  產生的錯誤訊息。但是這個解決方法很爛，而且只會讓未來越來越難 debug。
> WORKAROUND: Catch Error from Capacitor.Filesystem.deleteFile on Android or iOS Devices

- src/app/services/publisher/numbers-storage/numbers-storage-api.service.ts
- iOS inbox accept fails
Safari and iOS Webview implement a strict policy on HTTP redirection, dropping the auth headers on HTTP 301 redirect which is the behavior when the API receives a url not ended with slash.
> Fix the get Asset URL to prevent auth header to be dropped on iOS

- src/app/pages/home/home.page.html
- src/app/pages/home/home.page.scss
- src/app/pages/home/home.page.ts
- Change data flow to allow undefined asset so that upload failure doesn't prevent the view from updating.
- Display semi-transparent white overlay and error icon when upload fails. Clicking the overlay triggers re-uploading.
- Display uploading spinner when re-uploading.
- The user can only re-upload 1 photo at a time. During the upload, tapping the other upload-error photos does nothing.
- When uploading the photo in the normal flow, the user would see the upload error first (after the proof is added to the repository but before the asset is added to the repository)
It seems to me that trying to remove these limitations without adding a persistent upload state for Proof would make the component data flow very dirty. Feature-wise I believe the current limitation is acceptable so maybe we …
> Implement the not-uploaded overlay and re-upload click event for Captures

- src/app/services/dia-backend/auth/dia-backend-auth.service.ts
- src/app/services/image-store/image-store.service.ts
Completely migrate the `DiaBackendAuthService` from old `NumbersStoragePublisher` class. This migration has been tested on web and Android devices with 0.7.5 to 0.11.4 update. The previous failure is caused by the auth `token` contains `token ` string in the old version but not in the latest one.
> Fix dia backend auth migrate

- src/app/pages/home/home.page.html
- src/app/pages/home/home.page.scss
See #331. The repeated thumbnail for captures is fixed by setting the `background-size` CSS property to `cover`. The fix has been tested on web and Exodus 1s.
> Change the background-size to cover for capture thumbs.

- src/app/services/image-store/image-store.service.spec.ts
- src/app/services/image-store/image-store.service.ts
- src/app/services/repositories/proof/proof.ts
- src/app/utils/mime-type.ts
Add file extension to the images stored in `ImageStore` in order to successfully share files with Capacitor `Share` plugin. We do not need to migrate the data if we merge this PR in next release.
> Add extension to the image stored in ImageStore.

- src/app/services/dia-backend/asset/dia-backend-asset-repository.service.ts
Append slash in delete asset API endpoint to prevent iOS webview dropping auth header when HTTP redirection.
> Fix iOS DIA backend delete error

- src/app/pages/home/asset/asset.page.ts
- src/app/pages/home/asset/information/information.page.ts
- src/app/pages/home/asset/sending-post-capture/sending-post-capture.page.ts
- src/app/pages/home/inbox/inbox.page.ts
- src/app/pages/home/transaction/transaction-details/transaction-details.page.ts
- src/app/pages/home/transaction/transaction.page.ts
- src/app/services/dia-backend/asset/dia-backend-asset-repository.service.ts
- tslint.json
Introduce yet another workaround for clear the unsynced catch regarding PostCapture deletion. Also, use `shareReplay({bufferSize: 1, refCount: true})` to replace `share()` to avoid the shared `Observable` from not emitting on subscribe.
> WORKAROUND: Fix Unable to Send PostCaptures

- src/app/shared/services/collector/facts/capacitor-facts-provider/capacitor-facts-provider.service.ts
- src/app/shared/services/geolocation/geolocation.service.spec.ts
- src/app/shared/services/geolocation/geolocation.service.ts
- Implement the customized geolocation cache policy. See the latest details on miro.
- Change interface `GeolocationPositionError` to class `GeolocationError` to use `instanceof` to check the error type safely.
> Rebuild Capture - Step E2 (Customized Geolocation Cache Policy)

- src/app/features/home/capture-tab/capture-details/capture-details.page.ts
- src/app/features/home/capture-tab/capture-tab.component.html
- src/app/features/home/capture-tab/capture-tab.component.scss
- src/app/shared/services/database/table/capacitor-filesystem-table/capacitor-filesystem-table.spec.ts
- src/app/shared/services/database/table/capacitor-filesystem-table/capacitor-filesystem-table.ts
- src/app/shared/services/database/table/table.ts
- src/app/shared/services/dia-backend/asset/dia-backend-asset-repository.service.ts
- src/app/shared/services/dia-backend/transaction/ignored-transaction-repository.service.ts
- src/app/shared/services/repositories/proof/proof-repository.service.ts
- Merge E1 into rebuild-capture branch.
- Show a spinner when loading captures on capture tab.
- Use `undefined` as the initial value of `Database.Table.tuple$` and make `queryAll$` emit value if `isNonNullable`.
> Rebuild Capture - E3 (Show Spinner on Loading Captures)

- src/app/features/home/capture-tab/capture-details/capture-details.page.ts
- src/app/features/home/capture-tab/capture-details/sending-post-capture/sending-post-capture.page.html
- src/app/features/home/capture-tab/capture-details/sending-post-capture/sending-post-capture.page.ts
- src/app/features/home/post-capture-tab/post-capture-tab.component.scss
- src/app/features/home/post-capture-tab/post-capture-tab.component.ts
- src/app/shared/core/post-capture-card/post-capture-card.component.ts
- src/app/shared/services/dia-backend/asset/dia-backend-asset-repository.service.ts
- src/app/shared/services/share/share.service.spec.ts
- src/app/shared/services/share/share.service.ts
- Remove unneeded bottom margin in `PostCatpureTabComponent`
- Move sharing functionality to `ShareService`
- Add a fallback for sharing; if merging with `sharable_copy` url fails (most likely because of CORS error), catch the error and use download API instead. It's implemented as fallback since the former method does not always fails and is usually faster than the latter method.
- Fix broken back button in `SendPostCapturePage`
- PostCaptures will be re-fetched whenever the user navigated to HomePage from other pages, in addition to the re-fetching triggered by switching from CaptureTab to PostCaptureTab
- Fix possible race conditions in `PostCaptureTabComponent` with messy code. All fetching are handled in a single subscription.
> Rebuild Capture G1

- src/app/features/home/home.page.spec.ts
- src/app/features/home/post-capture-tab/post-capture-tab.component.spec.ts
Fix HomePage creation testing and missing VirtualScrollerModule import.
PostCaptureTabComponent failed to be created and the fix is not yet found, so it is disabled.
> Fix test errors in G1

- angular.json
- package-lock.json
- package.json
Add the icon font package and the corresponding config. Angular CLI will pack the icon-font with Webpack automatically.
> Add Offline Material Iconfont

- src/app/features/home/home.page.ts
- src/app/features/home/onboarding/prefetching-dialog/prefetching-dialog.component.ts
- src/app/shared/services/dia-backend/asset/dia-backend-asset-repository.service.ts
- src/app/shared/services/onboarding/onboarding.service.ts
- Pre-fetching is only invoked when newly logged in, so storing a isPrefetched preference is no longer needed. It is replaced by checking the remote asset count which also prevents asking a new user to confirm pre-fetching.
> Determine pre-fetching by remote asset count

- src/app/features/home/home.page.ts
- src/app/features/home/onboarding/prefetching-dialog/prefetching-dialog.component.ts
- src/app/shared/services/migration/migration.service.ts
- src/app/shared/services/onboarding/onboarding.service.ts
- Remove `isNewLogin` condition wrapping `redirectOnboarding()` on home page.
- Set `isNewLogin` to `false` before checking if to prefetch dialog.
- Set `hasPrefetchedDiaBackendAssets` to `true` after migration.
> Fix onboarding flow

- ios/App/App/Info.plist
- src/global.scss
- Fix the toolbar height on iOS
- Revert the change to hide status bar on iOS
> Fix iOS toolbar on Activity and CaptureDetails page

- src/app/shared/services/image-store/image-store.service.ts
- src/app/shared/services/repositories/proof/proof.ts
Add `OnWriteExistStrategy.IGNORE` to avoid write the file again if the file has already existed.
> Avoid duplicate write when setAsset in Proof.

- src/app/features/home/onboarding/prefetching-dialog/prefetching-dialog.component.ts
- src/app/shared/services/migration/migration.service.ts
Fix the following conditions:
- If an error happens during migrating, the migration dialog will not be closed.
- If an error happens during migrating, the`HAS_PREFETCHED_DIA_BACKEND_ASSETS` preference will not be set to true while it should.
- If network is not connected (assuming that user is using the App offline), the migrating dialog will prompt and disappear everytime the user navigates to the home page.
- If an error happens during pre-fetching, the pre-fetching dialog will not be closed.
> Fix migrating set has prefetch corner case

- src/app/features/login/login.page.ts
The minimal change that fixes the issue that the login error message does not pop up after the API error response schema changes.
> Fix handling of login HttpErrorResponse

- src/app/features/home/transaction/transaction-details/transaction-details.page.scss
- src/app/features/home/transaction/transaction-details/transaction-details.page.ts
- src/app/features/home/transaction/transaction.page.scss
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
According to the slack discussion:
> __@tammyyang__ 
> - asset 是我的 => 實心
> - asset 是別人的 => 空心
>
> 如果確定就是這個行為的話，就定下來
> QA 以後就用這個標準測
>
> __@wcchung__
> 這個標準我覺得也 OK，那目前就是接受者退回的 icon 需要改成空心
> Display stroked status style if the asset is not owned by the user.

- src/app/features/profile/profile.page.ts
- src/app/shared/services/database/database.service.spec.ts
- src/app/shared/services/database/database.service.ts
- src/app/shared/services/database/table/capacitor-filesystem-table/capacitor-filesystem-table.spec.ts
- src/app/shared/services/database/table/capacitor-filesystem-table/capacitor-filesystem-table.ts
- src/app/shared/services/database/table/table.ts
- src/app/shared/services/image-store/image-store.service.spec.ts
- src/app/shared/services/image-store/image-store.service.ts
- src/app/shared/services/preference-manager/preference-manager.service.spec.ts
- src/app/shared/services/preference-manager/preference-manager.service.ts
- src/app/shared/services/preference-manager/preferences/capacitor-storage-preferences/capacitor-storage-preferences.spec.ts
- src/app/shared/services/preference-manager/preferences/capacitor-storage-preferences/capacitor-storage-preferences.ts
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
See #369. This PR has several changes regarding data persistence.
- Add `clear` method on `Database`.
- Add `clear` method on `Table` interface.
- Add `clear` method on `PreferenceManager`.
- Adjust `clear` method on `Preferences` interface.
- Each preference will be `undefined` after being `clear`ed.
- Each preference `Observable` will __NOT__ emit new value after being `clear`ed (with `isNonNullable` operator).
- Each preference `Promise` will emit the default value after being `clear`ed.
- Adjust function types on `Preferences` implementations.
- Add `clear` method on `ImageStore`.
- After `DiaBackendAuthService.logout$()`
- Clear all user data: `ImageStore`, `Database` and `PreferenceManager`.
- Reload the app to re-initialize app.
This PR has been tested on Brave browser and Exodus …
> Remove all user data on logging out.

- src/app/features/home/capture-tab/capture-details/capture-details.page.html
- src/app/features/home/capture-tab/capture-details/capture-details.page.ts
The maps will be opened with Capacitor `Browser` plugin. Thus, the map would be the website of Google map instead of Google map app.
This PR has been tested on Brave browser and Exodus 1.
> Open Google maps with external URL on clicking location info.

- src/app/features/home/capture-tab/capture-details/options-menu/options-menu.component.html
- src/app/features/home/capture-tab/capture-details/options-menu/options-menu.component.ts
- src/app/features/home/capture-tab/capture-details/sending-post-capture/sending-post-capture.page.html
- src/app/features/home/capture-tab/capture-details/sending-post-capture/sending-post-capture.page.ts
- src/app/shared/core/post-capture-card/post-capture-card.component.html
- src/app/shared/core/post-capture-card/post-capture-card.component.scss
- src/app/shared/services/dia-backend/asset/dia-backend-asset-repository.service.ts
- src/app/shared/services/dia-backend/asset/uploading/dia-backend-asset-uploading.service.ts
Improve the register performance by
- Using offline preview image on sending-post-capture page.
- Checking if `sharable_copy` is available from the backend before showing share moment option on capture-details page.
The PR has been tested on Brave browser and Exodus 1.
> Improve register performance

- package-lock.json
- package.json
- src/app/features/home/capture-tab/capture-details/capture-details.page.ts
- src/app/features/home/capture-tab/capture-tab.component.html
- src/app/features/home/capture-tab/capture-tab.component.scss
- src/app/features/home/capture-tab/capture-tab.component.spec.ts
- src/app/features/home/capture-tab/capture-tab.component.ts
- src/app/features/home/home-routing.module.ts
- src/app/features/home/home.module.ts
- src/app/features/home/home.page.scss
- src/app/features/home/home.page.spec.ts
- src/app/features/home/post-capture-tab/post-capture-details/post-capture-details-routing.module.ts
- src/app/features/home/post-capture-tab/post-capture-details/post-capture-details.module.ts
- src/app/features/home/post-capture-tab/post-capture-details/post-capture-details.page.html
- src/app/features/home/post-capture-tab/post-capture-details/post-capture-details.page.scss
- src/app/features/home/post-capture-tab/post-capture-details/post-capture-details.page.spec.ts
- src/app/features/home/post-capture-tab/post-capture-details/post-capture-details.page.ts
- src/app/features/home/post-capture-tab/post-capture-tab.component.html
- src/app/features/home/post-capture-tab/post-capture-tab.component.scss
- src/app/features/home/post-capture-tab/post-capture-tab.component.spec.ts
- src/app/features/home/post-capture-tab/post-capture-tab.component.ts
- src/app/shared/services/dia-backend/asset/dia-backend-asset-repository.service.ts
See #555.
- Remove virtual-scroll on PostCapture tab.
- Update the layout on PostCapture tab to grid layout.
- Fetch all PostCaptures on focusing on PostCapture tab.
- Load PostCapture thumbnails lazily with `ion-img`.
- Implement a standalone `PostCaptureDetailsPage`, which cause a heavy code duplicate to the existent `CaptureDetailsPage`. However, as the UI and the data model of both Captures and PostCaptures will be changed significantly in the near future, this could be a temporary solution for easy adjustment.
> Update PostCapture grid layout

- src/app/features/home/post-capture-tab/post-capture-tab.component.html
- src/app/features/home/post-capture-tab/post-capture-tab.component.scss
- src/app/features/home/post-capture-tab/post-capture-tab.component.ts
According to the feedback from @tammyyang on Sprint and mid-sprint demo, we do not need to show the geolocation icon on PostCapture tab.
> Remove geolocation icon on PostCaptureTabComponent.

- .github/workflows/pre-release.yml
- src/app/features/home/post-capture-tab/post-capture-tab.component.html
- src/app/features/home/post-capture-tab/post-capture-tab.component.scss
- src/app/features/home/post-capture-tab/post-capture-tab.component.ts
- src/app/shared/services/dia-backend/asset/dia-backend-asset-repository.service.ts
According to [the discussion on Slack](https://dt42-numbers.slack.com/archives/CS29L7Z5H/p1615519385004100?thread_ts=1615515545.002100&cid=CS29L7Z5H), prefetch 9 PostCaptures on the tab initialization.
This PR has been tested on Brave browser and Exodus 1 with dev site.
> Prefetch partial PostCaptures on PostCapture tab init

- package.json
- src/app/features/home/capture-tab/capture-tab.component.html
- src/app/shared/services/image-store/image-store.service.spec.ts
- src/app/shared/services/image-store/image-store.service.ts
- src/app/shared/services/repositories/proof/proof.ts
- src/app/shared/shared.module.ts
Use `Filesystem.getUri()` method in Capacitor plugin to handle thumbnail request. The method does not work in browser, and thus need to check the environment before request URI. 
By doing so, we do not need to serialize/deserialize the image file to base64, which reduces some memory usage.
This PR has been tested on Brave browser and Exodus 1.
> Get Thumbnail src with URI instead of DataURL

- src/app/shared/services/image-store/image-store.service.ts
See #556. The performance does not gain benefit from using native file URL via `Filesystem.getUri` in mobile devices. Thus, we need to revert this change and find another way to further improve read performance in the future.
> Revert getting thumbnail URL with native getUri method

- src/app/features/home/home.page.scss
- src/app/features/home/post-capture-tab/post-capture-tab.component.html
- src/app/features/home/post-capture-tab/post-capture-tab.component.scss
fix  #578
頁面顯示當向下滑動時上方會有切割圖片的狀態
取消 padding-Top
> fix segment Occlude incomplete

- src/app/features/home/post-capture-tab/post-capture-details/post-capture-details.page.html
- src/app/features/home/post-capture-tab/post-capture-details/post-capture-details.page.ts
- src/app/features/home/post-capture-tab/post-capture-tab.component.ts
- src/app/shared/services/dia-backend/asset/dia-backend-asset-repository.service.ts
- src/app/shared/services/migration/migration.service.ts
See #554.
According to the discussion on mid-sprint kickoff, implement in-memory cache for PostCaptures to provide better UX.
- Cache PostCapture list response in memory.
- Cache PostCapture `asset_file` in memory.
- Possible thrashing with high `asset_file` quantity.
This is NOT an ideal cache implementation as we should build a safer and more structural LRU cache by leveraging declarative caching tool kits, such as `ngsw`. However, we do not have enought time for now.
> Implement memory cache for PostCaptures.

- src/app/features/home/post-capture-tab/post-capture-tab.component.html
- src/app/features/home/post-capture-tab/post-capture-tab.component.scss
According to the discussion of demo on 03/31/2021, we need to move the network status bar position below `ion-segment` on `PostCaptureTabComponent`.
> Make network status bar position consistent

- src/app/shared/services/dia-backend/asset/dia-backend-asset-repository.service.ts
It seems that `repeatWhen` does not work with endless observable.
> Fix: refreshPostCaptures not work with local cache.

- src/app/features/home/capture-tab/capture-item/capture-item.component.html
- src/app/features/home/capture-tab/capture-item/capture-item.component.scss
- src/app/features/home/capture-tab/capture-item/capture-item.component.ts
- src/app/features/home/post-capture-tab/post-capture-tab.component.html
- src/app/features/home/post-capture-tab/post-capture-tab.component.scss
- src/app/shared/pipes/starts-with/starts-with.pipe.spec.ts
- src/app/shared/pipes/starts-with/starts-with.pipe.ts
- src/app/shared/shared.module.ts
See [the discussion on Slack](https://dt42-numbers.slack.com/archives/C3CHPJTS4/p1618390525041500) and #630.
> Show video icon on thumbnail if the asset is video.

- src/app/features/home/transaction/transaction-details/transaction-details.page.html
- src/app/features/home/transaction/transaction.page.html
- src/app/utils/mime-type.ts
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
See #679.
- View GIF assets from DIA backend in app.
- View GIF PostCaptures received from friends in app.
- View GIF Captures uploaded with RESTful APIs in app.
- Delete GIF assets in app.
- Limitation: the size of GIF asset should be larger than 500 pixels to create sharable copy from DIA backend.
> Support GIF as Capture asset.

- android/.idea/compiler.xml
- android/.idea/misc.xml
- android/.idea/runConfigurations.xml
- src/app/features/home/capture-tab/capture-details/capture-details.page.ts
- src/app/features/home/home.page.ts
- src/app/features/profile/profile.page.ts
- src/app/shared/services/camera/camera.service.ts
- src/app/shared/services/capture/capture.service.ts
- src/app/shared/services/collector/collector.service.ts
- src/app/shared/services/dia-backend/asset/downloading/dia-backend-downloading.service.ts
- src/app/shared/services/media-store/media-store.service.ts
- src/app/shared/services/repositories/proof/old-proof-adapter.spec.ts
- src/app/shared/services/repositories/proof/old-proof-adapter.ts
- src/app/shared/services/repositories/proof/proof-repository.service.spec.ts
- src/app/shared/services/repositories/proof/proof-repository.service.ts
- src/app/shared/services/repositories/proof/proof.spec.ts
- src/app/shared/services/repositories/proof/proof.ts
- src/app/shared/services/share/share.service.ts
- src/app/utils/mime-type.ts
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
See #676.
- Unlimited recording time due to implementation limitation. See https://github.com/w3c/html-media-capture/issues/23 for details.
- Only support `video/mp4` and `video/quicktime` type with H.264 encoding.
- HTML media capture support list: https://caniuse.com/html-media-capture
- Update Android Studio environment configurations.
- Tested on Exodus 1 with latest webview version.
> Support video recording.

- src/app/features/home/home.page.html
- src/app/features/home/home.page.scss
- src/app/shared/media/media-store/media-store.service.ts
- src/index.html
Improve the initial loading time and priority of Home page
- Use file URL instead of data URI for thumbnails to truly enable lazy loading
- Preload launcher.svg
- Remove unneeded remote Material Icon source
- Replace ion-icon which loads slowly at App startup with mat-icon
> Feature improve home loading time

- android/app/src/main/java/io/numbersprotocol/capturelite/MainActivity.java
- src/app/features/home/capture-tab/capture-tab.component.html
- src/app/features/home/capture-tab/capture-tab.component.scss
- src/app/features/home/capture-tab/capture-tab.component.ts
- src/app/features/home/home.page.html
- src/app/shared/dia-backend/asset/refreshing/dia-backend-asset-refreshing.service.spec.ts
- src/app/shared/dia-backend/asset/refreshing/dia-backend-asset-refreshing.service.ts
- src/theme/variables.scss
Fix for #837 
- At homepage, users can pull down to refresh their captures now
- [known issue] If the device refresh too soon after a capture is taken at another device, the new capture can be shown but the thumbnail cannot displayed properly
> Add refresher on homepage to refresh captures

- src/app/features/home/details/details.page.scss
- src/app/features/home/sending-post-capture/sending-post-capture.page.scss
- src/app/shared/media/component/media.component.html
- src/app/shared/media/component/media.component.scss
#843 
- Show capture images/videos in their original aspect instead of fixed 1:1 ratio, which will usually crop them
> Feature not cropping videos and images

- src/app/shared/dia-backend/asset/dia-backend-asset-repository.service.ts
- src/app/shared/share/share.service.ts
#844 
- Share CAI-injected photo so that photos can speak for themselves
- Shared photo can be parsed by [media-reader](https://authmedia.net/media-reader) only when sharing them as "files" (e.g. sharing with gmail/gdrive, etc) 
- iOS: Share as "saving to files" instead of "saving to photos"
- APPs like instagram, facebook will compress the photo and the photo can not be parsed with our [media-reader](https://authmedia.net/media-reader)
> Share cai-injected photo instead of sharable copy

- src/app/features/home/home.page.html
- src/app/features/profile/phone-verification/phone-verification.page.ts
#839 
- Fix duplicate paste issue (verification code form for phone verification)
- Fix homepage sidebar display issue (before & after):
- For `formly-form`, there's duplicate paste issue on iOS if using input type `tel`
> Fix duplicate paste issue (verification code form for phone verification)

- src/app/features/profile/phone-verification/phone-verification.page.ts
Note
The behavior of all types being used as verification code:
- `tel`: keyboard: only digits, issue: double-paste
- `number`: keyboard: digits + punctuation marks, issue: incorrect code validation
- `text`: keyboard: normal alphabet keyboard (need to switch), issue: N/A
> fix: use text type to prevent incorrect code length validation

- android/.idea/misc.xml
- android/app/src/main/AndroidManifest.xml
- Fix `Unable to resolve camera activity` issue on Pixel 5 (Android 11, API level 30)
Reference: [bug: Android 11 - Unable to resolve camera activity #3627](https://github.com/ionic-team/capacitor/issues/3627#issuecomment-741703368)
> fix(AndroidManifest.xml): add IMAGE_CAPTURE query intent

- src/app/features/home/details/actions/actions.page.ts
- src/app/shared/actions/actions-dialog/actions-dialog.component.html
- src/app/shared/actions/actions-dialog/actions-dialog.component.spec.ts
- src/app/shared/actions/actions-dialog/actions-dialog.component.ts
- src/app/shared/actions/service/actions.service.spec.ts
- src/app/shared/actions/service/actions.service.ts
- src/app/shared/shared.module.ts
#1049 
* Use `mat-dialog` instead of `ionic alert` to support multiple types of input
* text input
* number input
* dropdown (select)
* Display more information about each input
* Checking the input when submitting the form
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1201515367303313) by [Unito](https://www.unito.io)
> add(actions-dialog): add action parameter selection dialog

- src/app/features/profile/profile.page.html
- src/app/features/profile/profile.page.ts
- src/app/shared/export-private-key-modal/export-private-key-modal.component.html
- src/app/shared/export-private-key-modal/export-private-key-modal.component.scss
- src/app/shared/export-private-key-modal/export-private-key-modal.component.spec.ts
- src/app/shared/export-private-key-modal/export-private-key-modal.component.ts
- src/app/shared/shared.module.ts
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
- User can see their private key after confirming with the warnings
Current UX flow:
1. Click "Export Private Key" button
2. Show the warnings. If proceed, go to step 3. Otherwise, the flow is ended
3. Show the private key, and user can copy to clipboard
> feat(profile.page): do not show user's private key directly

- src/app/features/home/details/actions/actions.page.html
- src/app/features/home/details/actions/actions.page.ts
- src/app/shared/actions/service/actions.service.ts
- src/app/shared/dia-backend/store/dia-backend-store.service.spec.ts
- src/app/shared/dia-backend/store/dia-backend-store.service.ts
- src/app/shared/order-detail-dialog/order-detail-dialog.component.html
- src/app/shared/order-detail-dialog/order-detail-dialog.component.spec.ts
- src/app/shared/order-detail-dialog/order-detail-dialog.component.ts
- src/app/shared/shared.module.ts
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
Support  NUM payment for Network APPs
* Add `dia-backend-store.service`: create network app order, confirm network app order.
* Add `order-detail-dialog.component`: display order detail before confirming the order.
* Modify the flow when submitting Network APP request.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1201651086081455) by [Unito](https://www.unito.io)
> Feature support num payment

- README.md
Update README.md Getting Started section to instruct users to export `NUMBERS_STORAGE_TRUSTED_CLIENT_KEY` and `NUMBERS_BUBBLE_DB_URL` in addition to  `NUMBERS_STORAGE_BASE_URL`.
> Update README Getting Started

- CHANGELOG.md
- android/app/build.gradle
- package-lock.json
- package.json
Bump version to 0.48.0 by following [README Release section](https://github.com/numbersprotocol/capture-lite#release).
> build: bump version to 0.48.0

- src/app/shared/dia-backend/wallet/dia-backend-wallet.service.ts
Update the api request url endpoint in `getManagedWallet$` to show NUM balance from custody/managed wallet instead of Capture wallet.
Dev storage backend
Prod storage backend
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1201813627329196) by [Unito](https://www.unito.io)
> feat(dia-backend-wallet.service.ts): show custody wallet balance

- src/app/features/profile/profile.page.html
- src/app/features/profile/profile.page.ts
- src/app/shared/dia-backend/wallet/dia-backend-wallet.service.ts
See [NUM balance does not load instantly #1277](https://github.com/numbersprotocol/capture-lite/issues/1277) for more context.
Demo: [before](https://www.youtube.com/watch?v=RISbs5wqb3c), [after](https://www.youtube.com/watch?v=RANjEGdR8Gk)
```bash
➜  capture-lite git:(feature-add-NUM-balance-loading-indicator) npm run test.ci
> capture-lite@0.48.1 test.ci
> capture-lite@0.48.1 preconfig
A secret file has generated successfully at ./src/app/shared/dia-backend/secret.ts
16 02 2022 12:40:01.660:INFO [karma-server]: Karma v6.3.16 server started at http://localhost:9876/
16 02 2022 12:40:01.661:INFO [launcher]: Launching browsers ChromeHeadlessCI with concurrency …
```
> Add num balance loading indicator

- src/app/features/home/details/details.page.html
- src/app/features/home/details/details.page.scss
Thanks for Charles’ suggestion. Add an edit icon when the asset caption is empty to inform users that they could tap to edit.
```bash
➜  capture-lite git:(feature-caption-edit-icon) ✗ npm run test.ci
> capture-lite@0.49.0 test.ci
> capture-lite@0.49.0 preconfig
A secret file has generated successfully at ./src/app/shared/dia-backend/secret.ts
22 02 2022 17:17:51.881:INFO [karma-server]: Karma v6.3.4 server started at http://localhost:9876/
22 02 2022 17:17:51.882:INFO [launcher]: Launching browsers ChromeHeadlessCI with concurrency unlimited
22 02 2022 17:17:51.884:INFO [launcher]: Starting browser ChromeHeadless
22 02 2022 17:17:58.280:INFO [Chrome Headless …
```
> feat(src/app/features/home/details): display edit icon when no caption

- src/app/features/home/sending-post-capture/sending-post-capture.page.html
- src/app/features/home/sending-post-capture/sending-post-capture.page.ts
* Hide the add to contacts checkbox if the receiver is already in user's contacts
* Update the appearance of add to contacts checkbox 
Before:
After: 
```bash
➜  capture-lite git:(feature-remove-add-to-contacts-checkbox-when-receiver-already-in-contacts) ✗ npm run test.ci
> capture-lite@0.49.1 test.ci
> capture-lite@0.49.1 preconfig
02 03 2022 21:01:33.042:INFO [karma-server]: Karma v6.3.4 server started at http://localhost:9876/
02 03 2022 21:01:33.043:INFO [launcher]: Launching browsers ChromeHeadlessCI with concurrency unlimited
02 03 2022 21:01:33.045:INFO [launcher]: Starting …
```
> Feature remove add to contacts checkbox when receiver already in contacts

- src/app/features/wallets/wallets.page.html
- src/app/features/wallets/wallets.page.ts
- src/app/shared/dia-backend/auth/dia-backend-auth.service.ts
- Support points system and connect it to the backend
- Hide buy NUM button
```bash
➜  capture-lite git:(feature-support-points-hide-buy-num) ✗ npm run test.ci                                                   
> capture-lite@0.50.0 test.ci
> capture-lite@0.50.0 preconfig
16 03 2022 14:44:56.097:INFO [karma-server]: Karma v6.3.4 server started at http://localhost:9876/
16 03 2022 14:44:56.098:INFO [launcher]: Launching browsers ChromeHeadlessCI with concurrency unlimited
16 03 2022 14:44:56.100:INFO [launcher]: Starting browser ChromeHeadless
16 03 2022 14:45:02.673:INFO [Chrome …
```
> feat: support points system and connect it to the backend and hide buy NUM button

- src/app/features/home/details/actions/actions.page.ts
Fix network action order history generated even when confirm order failed
Before: https://youtu.be/yGyEsLqA75Q
After: https://youtu.be/nV6KU0MOnBk
```bash
➜  capture-lite git:(fix-network-action-order-history-generated-even-when-confirm-order-failed) npm run test.ci
> capture-lite@0.50.0 test.ci
> capture-lite@0.50.0 preconfig
16 03 2022 16:09:51.970:INFO [karma-server]: Karma v6.3.4 server started at http://localhost:9876/
16 03 2022 16:09:51.971:INFO [launcher]: Launching browsers ChromeHeadlessCI with concurrency unlimited
16 03 2022 16:09:51.973:INFO [launcher]: Starting browser …
```
> Fix network action order history generated even when confirm order failed

- src/app/features/home/activities/activities.page.html
- src/app/features/home/details/actions/actions.page.html
- src/app/features/home/details/details.page.ts
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
Rename more actions to network actions.
```bash
➜  capture-lite git:(fix-rename-more-actions-to-network-actions) ✗ npm run test.ci
> capture-lite@0.50.1 test.ci
> capture-lite@0.50.1 preconfig
21 03 2022 22:09:20.800:INFO [karma-server]: Karma v6.3.4 server started at http://localhost:9876/
21 03 2022 22:09:20.801:INFO [launcher]: Launching browsers ChromeHeadlessCI with concurrency unlimited
21 03 2022 22:09:20.803:INFO [launcher]: Starting browser ChromeHeadless
21 03 2022 22:09:27.463:INFO [Chrome Headless 99.0.4844.74 (Mac OS 10.15.7)]: Connected on socket pdCJntRc5A3iV4DhAAAB …
```
> fix: rename more actions to network actions

- src/app/features/home/activities/capture-transaction-details/capture-transaction-details.page.html
- src/app/features/home/activities/capture-transaction-details/capture-transaction-details.page.scss
Fix ios activity details page cid overflow. I add `max-width: 90%;` to `mat-label` so now it should never overflow.
Screenshot from my iPhone:
```bash
➜  capture-lite git:(fix-ios-activity-details-cid-overflow) ✗ npm run test.ci
> capture-lite@0.50.1 test.ci
> capture-lite@0.50.1 preconfig
21 03 2022 21:15:36.571:INFO [karma-server]: Karma v6.3.4 server started at http://localhost:9876/
21 03 2022 21:15:36.573:INFO [launcher]: Launching browsers ChromeHeadlessCI with concurrency unlimited
21 03 2022 21:15:36.575:INFO [launcher]: Starting browser ChromeHeadless
21 03 2022 …
```
> fix: fix ios activity details page cid overflow

- src/app/shared/actions/actions-dialog/actions-dialog.component.ts
- src/app/shared/actions/service/actions.service.ts
Support optional network action parameters.
Notice that user can proceed without entering the remaining 2 fields.
```bash
➜  capture-lite git:(feature-support-optional-network-action-params) npm run test.ci
> capture-lite@0.52.1 test.ci
> capture-lite@0.52.1 preconfig
28 03 2022 14:29:01.263:INFO [karma-server]: Karma v6.3.4 server started at http://localhost:9876/
28 03 2022 14:29:01.264:INFO [launcher]: Launching browsers ChromeHeadlessCI with concurrency unlimited
28 03 2022 14:29:01.265:INFO [launcher]: Starting browser ChromeHeadless
28 03 2022 14:29:08.198:INFO [Chrome Headless …
```
> feat: support optional network action parameters

- src/app/features/home/details/actions/actions.page.ts
- src/app/shared/actions/service/actions.service.ts
Support 0 parameter network action. Previously the app would throw error if a network action does not have any parameters.
Demo:
```bash
➜  capture-lite git:(feature-support-0-parameter-network-action) npm run test.ci
> capture-lite@0.52.1 test.ci
> capture-lite@0.52.1 preconfig
Compiling @angular/core/testing : es2015 as esm2015
Compiling @angular/platform-browser/testing : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling @angular/common/testing : es2015 as esm2015
Compiling @angular/common/http/testing : es2015 as esm2015
Compiling …
```
> feat: support 0 parameter network action

- src/app/features/home/activities/capture-transactions/capture-transactions.component.html
- src/app/features/home/activities/capture-transactions/capture-transactions.component.scss
- src/app/features/home/activities/capture-transactions/capture-transactions.component.ts
Add loading indicator at capture transactions history page.
Maybe we could cache this locally and pull from backend only when user pull to refresh. Same for network action orders history.
```bash
➜  capture-lite git:(feature-add-loading-indicator-at-capture-transactions-page) ✗ npm run test.ci
> capture-lite@0.52.1 test.ci
> capture-lite@0.52.1 preconfig
28 03 2022 12:01:23.998:INFO [karma-server]: Karma v6.3.4 server started at http://localhost:9876/
28 03 2022 12:01:23.998:INFO [launcher]: Launching browsers ChromeHeadlessCI with concurrency unlimited
28 03 2022 12:01:24.000:INFO …
```
> feat: add loading indicator at capture transactions history page

- src/app/features/home/details/actions/actions.page.ts
- src/app/shared/dia-backend/store/dia-backend-store.service.ts
- src/app/shared/dia-backend/wallet/dia-backend-wallet.service.ts
- src/app/shared/order-detail-dialog/order-detail-dialog.component.html
- src/app/shared/order-detail-dialog/order-detail-dialog.component.ts
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
Show insufficient NUM in order confirm dialog if applicable.
```bash
➜  capture-lite git:(feature-show-insufficient-NUM-in-order-confirm-dialog) npm run test.ci
> capture-lite@0.52.1 test.ci
> capture-lite@0.52.1 preconfig
30 03 2022 18:29:20.243:INFO [karma-server]: Karma v6.3.4 server started at http://localhost:9876/
30 03 2022 18:29:20.244:INFO [launcher]: Launching browsers ChromeHeadlessCI with concurrency unlimited
30 03 2022 18:29:20.247:INFO [launcher]: Starting browser ChromeHeadless
30 03 2022 18:29:27.406:INFO [Chrome Headless 99.0.4844.84 (Mac OS 10.15.7)]: Connected on …
```
> feat: show insufficient NUM in order confirm dialog if applicable

- CHANGELOG.md
- android/app/build.gradle
- package-lock.json
- package.json
> build: bump version to 0.53.0

- src/app/features/wallets/transfer/transfer.page.html
- src/app/features/wallets/transfer/transfer.page.scss
- src/app/features/wallets/wallets.page.html
- src/app/features/wallets/wallets.page.scss
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202073304227539) by [Unito](https://www.unito.io)
> Feature adjust wallet page and transfer page UI for screen size less than 360px with media query

- src/app/features/home/capture-tab/capture-tab.component.ts
- src/app/features/home/details/information/session/information-session.service.ts
- src/app/shared/dia-backend/asset/dia-backend-asset-repository.service.ts
- src/app/shared/dia-backend/asset/downloading/dia-backend-downloading.service.ts
- src/app/shared/dia-backend/asset/refreshing/dia-backend-asset-refreshing.service.ts
* Download asset thumbnail and asset file through cdn
* Fix refresh not working when there's no Capture
https://www.youtube.com/shorts/MQ9c4NMVnMQ
https://youtube.com/shorts/GPakD0a0Seo?feature=share
```bash
➜  capture-lite git:(feature-download-asset-using-cdn) npm run test.ci
> capture-lite@0.53.0 test.ci
> capture-lite@0.53.0 preconfig
31 03 2022 21:47:32.761:INFO [karma-server]: Karma v6.3.4 server started at http://localhost:9876/
31 03 2022 21:47:32.762:INFO [launcher]: Launching browsers ChromeHeadlessCI with concurrency unlimited
31 03 2022 21:47:32.765:INFO [launcher]: …
```
> Feature download asset using cdn

- src/app/features/wallets/wallets.page.html
- src/app/features/wallets/wallets.page.ts
Implement buy NUM button and have it point to https://buy.num.indacoin.io/. See https://github.com/numbersprotocol/capture-lite/issues/1469
Demo: https://youtube.com/shorts/m4feXidjmwE?feature=share
```bash
➜  capture-lite git:(feature-buy-num-button) npm run test.ci
> capture-lite@0.53.0 test.ci
> capture-lite@0.53.0 preconfig
01 04 2022 22:09:58.794:INFO [karma-server]: Karma v6.3.4 server started at http://localhost:9876/
01 04 2022 22:09:58.795:INFO [launcher]: Launching browsers ChromeHeadlessCI with concurrency unlimited
01 04 2022 22:09:58.797:INFO [launcher]: Starting browser …
```
> feat: implement buy NUM button

- src/app/shared/dia-backend/asset/downloading/dia-backend-downloading.service.ts
- src/app/shared/dia-backend/asset/prefetching/dia-backend-asset-prefetching.service.ts
- src/app/shared/media/media-store/media-store.service.ts
Skip storing asset thumbnail for assets that have already been cached locally. I believe asset thumbnail won't really changed once they're created. So why store it each time we refresh?
This should reduce backend workload and significantly improve Capture App refresh performance : )
https://youtu.be/pgW3wliFn_A
https://youtu.be/95QD1v8YOn4
```bash
➜  capture-lite git:(feature-skip-storing-thumbnail-for-cached-assets) npm run test.ci
> capture-lite@0.53.0 test.ci
> capture-lite@0.53.0 preconfig
06 04 2022 17:40:11.771:INFO [karma-server]: Karma v6.3.4 server started at …
```
> feat: skip storing asset thumbnail for cached assets

- src/app/features/home/capture-tab/capture-item/capture-item.component.html
- src/app/features/home/capture-tab/capture-item/capture-item.component.scss
- src/app/features/home/capture-tab/capture-item/capture-item.component.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202071964488862) by [Unito](https://www.unito.io)
> feat: add icon to indicate capture with caption

- CHANGELOG.md
- android/app/build.gradle
- package-lock.json
- package.json
- src/app/features/wallets/wallets.page.html
- Hide buy NUM button from Wallets page
- Bump version
in one branch
> Build bump 0.56.3

- src/app/shared/user-guide/user-guide.service.ts
The user guide is working fine on the Web and Android but as issues on iOS, therefore, I temporarily disable the user guide.
Today 0.57.2 should be published so I do not have enough time to fix it on iOS.
> temporarely hide in-app user guide

- src/app/features/signup/signup.page.ts
- src/app/shared/error/error.service.ts
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
[show the correct error message when user in sign up page](https://app.asana.com/0/1201016280880500/1202310913838280/f)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202350175850596) by [Unito](https://www.unito.io)
> fix(sign-up.page): convert generic backend error to more specific

- src/app/shared/share/share.service.ts
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202345530538071) by [Unito](https://www.unito.io)
> fix text for share referal code

- src/app/features/home/home.module.ts
- src/app/features/home/home.page.ts
- src/app/features/home/in-app-updates/update-app-dialog/update-app-dialog.component.html
- src/app/features/home/in-app-updates/update-app-dialog/update-app-dialog.component.spec.ts
- src/app/features/home/in-app-updates/update-app-dialog/update-app-dialog.component.ts
- src/app/shared/dia-backend/service/dia-backend-service.service.spec.ts
- src/app/shared/dia-backend/service/dia-backend-service.service.ts
- src/app/utils/date.ts
- src/app/utils/url.ts
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202415261106512) by [Unito](https://www.unito.io)
> Feature-in-app-upgrade-notifications

- src/app/features/home/custom-camera/custom-camera.page.html
- src/app/features/home/custom-camera/custom-camera.page.scss
- src/app/features/home/custom-camera/custom-camera.page.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202527286095325) by [Unito](https://www.unito.io)
> feat(custom-camera): add splash feedback on capture photo

- package-lock.json
- package.json
- src/app/features/wallets/wallets.module.ts
- src/app/features/wallets/wallets.page.html
- src/app/features/wallets/wallets.page.scss
- src/app/features/wallets/wallets.page.ts
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
This is the result of pull request
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202545955860671) by [Unito](https://www.unito.io)
> Feature qr code for deposit

- src/app/features/home/custom-camera/custom-camera-routing.module.ts
- src/app/features/home/custom-camera/custom-camera.module.ts
- src/app/features/home/custom-camera/custom-camera.page.html
- src/app/features/home/custom-camera/custom-camera.page.ts
- src/app/features/home/custom-camera/pre-publish-mode/pre-publish-mode.component.html
- src/app/features/home/custom-camera/pre-publish-mode/pre-publish-mode.component.scss
- src/app/features/home/custom-camera/pre-publish-mode/pre-publish-mode.component.spec.ts
- src/app/features/home/custom-camera/pre-publish-mode/pre-publish-mode.component.ts
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202592614295290) by [Unito](https://www.unito.io)
> add pre-view page before uploading capture

- src/app/features/home/home.page.ts
I accidentally disable the app version check at the app start (during local development). This commit enables app check at app start.
> fix(home.page): check app version at app launch

- set-secret.js
- src/app/features/home/details/details.page.ts
- src/app/features/home/explore-tab/explore-tab/explore-tab.component.ts
Feature changes
1. Make iframe URL configurable by adding `BUBBLE_IFRAME_URL` in `set-secret.js`.
2. Update the explorer and details pages to use `BUBBLE_IFRAME_URL` instead of the hard-coding URLs.
3. Add repository secret `NUMBERS_BUBBLE_IFRAME_URL`.
> Feature: Make iframe URL configurable

- src/app/features/home/capture-tab/capture-item/capture-item.component.ts
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
This PR prevents users from opening capture if it's not uploaded yet. Here is the [claap](https://app.claap.io/numbers-protocol/devs-only-open-capture-only-if-uploaded-c-O35CsUM4Uy-NJMagBX76oN_) demo
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203002972154612) by [Unito](https://www.unito.io)
> fix(capture-item): only open capture if uploaded

- src/app/features/home/custom-camera/custom-camera.page.ts
(Only Android) Camera update is something weird, the user flow is
1) take a photo
2) photo confirm page
when user press the previous step button(upper left button) then it back to camera page, it’s expectation. However, when user press the android back button then it will back to main page directly. The expectation android back button or previous step button should be the same.
[Demo](https://i.imgur.com/ASKaP12.mp4) of the PR.
Now when user click android back button it will go back as expected.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203012689781478) by [Unito](https://www.unito.io)
> fix(custom-camera): back button behaves as expected on Android

- src/app/app.component.ts
- src/app/features/home/home.page.html
Before I was loading icons directly from assets path, but after this commit I register icons first then load them. More detailed explanation is available at this [claap](https://app.claap.io/numbers-protocol/devs-q-and-a-only-fixing-tab-icons-c-O35CsUM4Uy-UD_VvzbEJMvV).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203048583466296) by [Unito](https://www.unito.io)
> fix tab bar icons load speed

- src/app/features/home/home.page.html
Remove "Capture Club" menu Item from drawer [[screenshot](https://i.imgur.com/lFQkU7J.png)].
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203096968395356) by [Unito](https://www.unito.io)
> fix(home-page): remove capture club from menu

- src/app/features/home/details/details.page.ts
- src/app/features/home/explore-tab/explore-tab/explore-tab.component.html
- src/app/features/home/explore-tab/explore-tab/explore-tab.component.ts
- src/app/shared/dia-backend/auth/dia-backend-auth.service.ts
- src/app/utils/date.ts
This PR will cache and reuse the Query JWT token. JWT token is valid for 5 minutes but I refresh the token if it's older than 4 minutes so we could have 1 minute in a buffer. Here is the [claap](https://app.claap.io/numbers-protocol/devs-only-reuse-jwt-token-from-cache-c-O35CsUM4Uy-poe6r5p-Gjag) for more details.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203054428002780) by [Unito](https://www.unito.io)
> Feature reuse jwt token

- src/app/shared/in-app-store/in-app-store.service.ts
Currently, I fetch num points price at app launch. This commit will fetch num points price on the walles page only. Here is the [claap](https://app.claap.io/numbers-protocol/dev-qa-only-fetch-num-point-price-on-wallets-page-open-c-O35CsUM4Uy-BFBipxBsRT8c) for a more detailed explanation.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203147410254210) by [Unito](https://www.unito.io)
> fix(in-app-store): request num points on wallets page only

- ios/App/App.xcodeproj/project.pbxproj
Here is the [claap](https://app.claap.io/numbers-protocol/dev-change-ios-provisioning-profile-to-numbers-app-distribution-v3-c-O35CsUM4Uy-7uQMe1fVOcan) explanation please have a look.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203213641846272) by [Unito](https://www.unito.io)
> change ios Provisioning Profile to NumbersAppDistributionV3

- src/app/features/home/capture-tab/capture-tab.component.html
A simple fix to remove duplicate network status. Here is the [claap](https://app.claap.io/numbers-protocol/dev-qa-demo-remove-duplicate-network-status-c-O35CsUM4Uy-zG90tZWRc0CY) demo.
NOTE:
Should be included for Oct 25, 2022 (Tuesday) release.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203213127063702) by [Unito](https://www.unito.io)
> fix(capture-tab): remove duplicate network status

- package-lock.json
Currently, recording video with an iOS front camera will crash the app. To fix an issue I have done some native development.
This PRs from [sultanmyrza](https://github.com/sultanmyrza)/[preview-camera](https://github.com/sultanmyrza/preview-camera) (also synced with [numbersprotocol/preview-camera](https://github.com/numbersprotocol/preview-camera))
* https://github.com/sultanmyrza/preview-camera/pull/16 (version 0.0.9)
* https://github.com/sultanmyrza/preview-camera/pull/17 (version 0.0.10)
will fix the issue iOS camera issue.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203225701370375) by [Unito](https://www.unito.io)
NOTE:
Should be included for Oct 25, 2022 (Tuesday) release.
> update @numbersprotocol/preview-camera plugin to version 0.10.0

- src/app/features/wallets/wallets.page.html
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
**NOTE:
Should be included for Oct 25, 2022 (Tuesday) release.**
Just change text from "integrity key" to "integrity wallet". Used existing translation.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203226425089271) by [Unito](https://www.unito.io)
> fix(wallets.page): text from itegrity key to integrity wallet

- .github/workflows/test.yml
Fix GitHub lint, test jobs (include pintura env key)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203276431793266) by [Unito](https://www.unito.io)
> fix(test.yml): generate npmrc before lint and test

- src/app/features/home/activities/network-action-order-details/network-action-order-details.page.html
- src/app/features/home/activities/network-action-order-details/network-action-order-details.page.ts
- src/app/utils/url.ts
NOTE: Should be included in the v221101 release.
This PR will generate the Result URL from the capture id. This PR closes 2 task at the same time.
* [✓ Result URL in the network app history should be the URL of Capture asset page](https://app.asana.com/0/1201016280880500/1203129620572131)
* [[issue] Lacking result url for “Share and explore” network action](https://app.asana.com/0/1201016280880500/1202494282094194)
Please see this asana [Comment by @Ethan Wu on Result URL in the network app history should be the URL of Capture asset page](https://app.asana.com/0/0/1203129620572131/1203275644094850/f)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203276742921315) by [Unito](https://www.unito.io)
> generate Result URL from capture id

- src/app/shared/media/media-store/media-store.service.ts
**NOTE: Should be included in the v221101 release.**
Currently for each capture we generate 100x100 pixels thumbnails. Now we generate 500x500 for a clearer picture.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203276696292707) by [Unito](https://www.unito.io)
> fix(media-store): generate 500x500 thumbnails

- ios/App/ExportOptions.plist
Currently, the **build-ios-prod job** is failing with error:
```
error: exportArchive: Provisioning profile "NumbersAppDistributionV2" doesn't include signing certificate "iPhone Distribution: Numbersprotocol Inc. (G7NB5YCKAP)".
```
I found 1 place where we still have `NumbersAppDistributionV2` and change it to `NumbersAppDistributionV4`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203279753344586) by [Unito](https://www.unito.io)
> fix GitHub build-ios-prod job

- src/app/features/home/explore-tab/explore-tab/explore-tab.component.html
- src/app/features/home/explore-tab/explore-tab/explore-tab.component.ts
- src/app/features/home/home.page.ts
- src/app/shared/android-back-button/android-back-button.service.ts
- src/app/shared/iframe/iframe.service.ts
**Part of v221115-capture-app-ionic release**
When the android back button is clicked it will navigate back iframe in explore tab. [Claap](https://app.claap.io/numbers-protocol/ionic-iframe-devs-android-back-button-working-for-iframe-c-O35CsUM4Uy-AfmrcRkKrMh4)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203343158313656) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1201016280880500/1203343158313656
> Fix iframe android back button navigation

- src/app/features/home/custom-camera/custom-camera.service.ts
**Part of release v221129-capture-app-ionic**
Before camera zoom was too sensitive (moving zoom slider zooms in too fast and too far). 
Here are the fixed [iOS](https://i.imgur.com/eQ01XKv.mp4) and [Android](https://i.imgur.com/Xuw1npx.mp4) demos.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203404264659297) by [Unito](https://www.unito.io)
> fix(custom-camera): zoom sensitivity

- src/app/shared/media/media-store/media-store.service.ts
**Part of v221125-capture-app-ionic**
Fix for [[FR] Allow users to archive assets from Capture App](https://app.asana.com/0/1201016280880500/1202798342707582/f) here is the [claap](https://app.claap.io/numbers-protocol/capture-delete-issue-fix-c-O35CsUM4Uy-g_X7fb0BAynA) explanation
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203438012082188) by [Unito](https://www.unito.io)
> fix(media-store): only ignore File Not Exist error

- capacitor.config.json
@bafu can we add this PR for tomorrow's release? Here is the [claap](https://app.claap.io/numbers-protocol/run-the-capacitor-web-server-on-android-under-https-c-O35CsUM4Uy-xIuEAf4lu7yS) explanation.
P.S: I set autogenerated task as a dependency for this task [[issue] Capture app doesn't allow Pixel6A user to confirm to register photos.
](https://app.asana.com/0/1201016280880500/1203175716103883/f)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203449413499957) by [Unito](https://www.unito.io)
> fix(capacitor.config): run Capacitor web server under https on Android

- src/app/features/home/custom-camera/custom-camera.page.ts
**Part of v221129-capture-app-ionic**
Before we were using `this.location.back();` to navigate back which works fine on iOS and Android. However, the QA reported that Pixel 6a use can not navigate back.
I was able to reproduce the issue and tried 3 versions to navigate back
- `this.navCtrl.back();` using NavController from "ionic/angular"
- `this.location.back();`
- `this.router.navigate(['..'])` worked on Android 6a
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203425374552216) by [Unito](https://www.unito.io)
> fix: custom camera back button nav via angular router

- ios/App/App.xcodeproj/project.pbxproj
- ios/App/App/Base.lproj/Main.storyboard
- ios/App/App/MyViewController.swift
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203484972839186) by [Unito](https://www.unito.io)
> fix: iOS iframe white flash with custom View Controller

- src/app/features/home/custom-camera/custom-camera.page.html
Hot fix to rename Story to Short in the custom camera page. Based on this slack [conversation](https://dt42-numbers.slack.com/archives/C43K663U0/p1671616022903489?thread_ts=1671612590.719659&cid=C43K663U0).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203593763476394) by [Unito](https://www.unito.io)
> fix(custom-camera.page): rename "STORY" to "SHORT"

- src/app/features/home/custom-camera/custom-camera.page.scss
Some iOS devices have a display cutouts, this PR should fix it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203601326768392) by [Unito](https://www.unito.io)
> fix: custom-camera header, footer size

- src/app/features/home/details/details.page.ts
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203594691107194) by [Unito](https://www.unito.io)
> fix: translation "view blockchain profile" to "view asset profile"

- src/app/shared/actions/actions-dialog/actions-dialog.component.ts
Here is the [claap](https://app.claap.io/numbers-protocol/qa-fix-ios-auto-focus-on-price-c-O35CsUM4Uy-k77oRpCXhwVq) explanation.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203609735058396) by [Unito](https://www.unito.io)
> fix(actions-dialog): force focus on first field [iOS only]

- src/app/features/wallets/transfer/transfer.page.scss
After applying white flash fix, some UI element colors are black.
One example was on android wallet page, card was black.
This is fix for transfer page text that become black. To fix it I manually set it to white.
> fix(transfer.page): change qr code text color to white

- src/app/features/wallets/wallets.page.scss
I set vertical alignment to the center. [demo](https://i.imgur.com/kr4GUdA.mp4)
> fix(wallet.page): align mainnet row items center

- .github/workflows/pre-release.yml
Inspired by this [post](https://hynek.me/til/set-output-deprecation-github-actions/). Tested on a [experiment](https://github.com/sultanmyrza/experiments-github-actions/blob/90ad31de085373066b1a06b373491e4c8a2c56fb/.github/workflows/sample.yml#L36) repo. Quick [claap](https://app.claap.io/numbers-protocol/bafu-or-tammy-update-capture-ci-scripts-for-git-hub-change-c-O35CsUM4Uy-Z-ruanoAoqZw) explanation.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203842559134622) by [Unito](https://www.unito.io)
> fix: CI deprecated github commands

- src/app/app.component.ts
- src/app/features/home/custom-camera/custom-camera.page.ts
- src/app/features/home/custom-camera/custom-camera.service.ts
- src/app/features/settings/go-pro/services/go-pro-media.service.ts
- src/app/features/settings/settings.page.ts
- src/app/features/wallets/wallets.page.ts
- src/app/shared/actions/service/order-history.service.ts
- src/app/shared/camera/camera.service.ts
- src/app/shared/capture/capture.service.ts
- src/app/shared/collector/collector.service.spec.ts
- src/app/shared/collector/collector.service.ts
- src/app/shared/collector/signature/capture-app-web-crypto-api-signature-provider/capture-app-web-crypto-api-signature-provider.service.spec.ts
- src/app/shared/collector/signature/capture-app-web-crypto-api-signature-provider/capture-app-web-crypto-api-signature-provider.service.ts
- src/app/shared/collector/signature/signature-provider.ts
- src/app/shared/migration/service/migration.service.ts
- src/app/shared/repositories/proof/proof.ts
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1204235734804980) by [Unito](https://www.unito.io)
> Feat v230223 v230310 special provider for photos taken from capture app

- .github/workflows/build-apks.yml
- Replace unmaintained Skicka package with rclone to upload APKs to Google Drive
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1204925844466679) by [Unito](https://www.unito.io)
> ci(build-apks.yml): use rclone to upload apks to Google Drive

- src/app/features/home/custom-camera/custom-camera.page.html
- src/app/features/home/custom-camera/custom-camera.page.ts
- src/app/features/home/custom-camera/pre-publish-mode/pre-publish-mode.component.ts
Fixes https://app.asana.com/0/1201083422707776/1205042457187289/f 
On androd 13 we need to copy temporarely copy image to cache as explained in WORKAROUND: https://github.com/numbersprotocol/capture-lite/issues/2904
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1205122623750227) by [Unito](https://www.unito.io)
> Fix v230711 issue User can’t register asset when using capture camera

- src/app/features/home/activities/activities.page.html
- src/app/features/home/activities/activities.page.scss
- src/app/features/home/activities/network-action-order-details/network-action-order-details.page.html
- src/app/features/home/activities/network-action-order-details/network-action-order-details.page.scss
- src/app/features/home/activities/network-action-order-details/network-action-order-details.page.ts
- src/app/features/home/activities/network-action-orders/network-action-orders.component.html
- src/app/features/home/activities/network-action-orders/network-action-orders.component.scss
- src/app/features/home/activities/network-action-orders/network-action-orders.component.ts
- src/app/shared/dia-backend/store/dia-backend-store.service.ts
- src/app/shared/iframe/iframe.ts
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
Closes https://github.com/numbersprotocol/capture-lite/issues/2658. Here is the [demo](https://app.claap.io/feat-v230725-showing-order-information-in-the-transaction-c-O35CsUM4Uy-Q4cwwujSE0SW)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1205201195637278) by [Unito](https://www.unito.io)
> Feature v230725 showing order information in the transaction

- src/app/features/signup/signup.page.ts
Fixes [[Issue] When user registers the account but user inputs the existing name, the error message is wrong.](https://app.asana.com/0/1201016280880500/1204125871819015/f)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1205841758848774) by [Unito](https://www.unito.io)
> fix(signup.page): show correct error message for duplicate username

- ios/App/App.xcodeproj/project.pbxproj
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1205852222739296) by [Unito](https://www.unito.io)
> fix: set iOS provisioning profile to NumbersAppDistributionV5

- package-lock.json
- package.json
- src/app/shared/collector/collector.service.ts
- src/app/shared/collector/signature/capture-app-web-crypto-api-signature-provider/capture-app-web-crypto-api-signature-provider.service.spec.ts
- src/app/shared/collector/signature/capture-app-web-crypto-api-signature-provider/capture-app-web-crypto-api-signature-provider.service.ts
- src/app/shared/dia-backend/asset/dia-backend-asset-repository.service.ts
- src/app/shared/repositories/proof/old-proof-adapter.ts
- src/app/shared/repositories/proof/proof.spec.ts
- src/app/shared/repositories/proof/proof.ts
- src/app/utils/nit/nit.ts
Fixes #2995, here is the [demo](https://app.claap.io/numbers-protocol/v231017-capture-cam-ionic-launch-c-O35CsUM4Uy-h0kmRSCHGdZb#c-Womf7UzmxvAwB29IATIGO) of e2e testing.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1205959614232507) by [Unito](https://www.unito.io)
> Feature add integrity sha on asset creation

- src/app/features/home/capture-tab/capture-item/capture-item.component.ts
- src/app/features/home/details/edit-caption/edit-caption.page.ts
- src/app/shared/dia-backend/asset/downloading/dia-backend-downloading.service.ts
- src/app/shared/repositories/proof/proof.ts
Fixes https://github.com/numbersprotocol/capture-lite/issues/3137. Here is the [demo](https://app.claap.io/numbers-protocol/issue-excessive-api-calls-during-reload-restore-captures-c-O35CsUM4Uy-ABZSjaXq23J3)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1206238750144946) by [Unito](https://www.unito.io)
> Fix excessive api call

- src/app/features/home/capture-tab/capture-tab.component.ts
- src/app/shared/dia-backend/asset/dia-backend-asset-repository.service.ts
- src/app/shared/dia-backend/asset/downloading/dia-backend-downloading.service.ts
- src/app/shared/dia-backend/asset/uploading/dia-backend-asset-uploading.service.ts
- src/app/shared/repositories/proof/proof.spec.ts
- src/app/shared/repositories/proof/proof.ts
Fixes https://github.com/numbersprotocol/capture-lite/issues/3138
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1206238554167570) by [Unito](https://www.unito.io)
> Feat sort assets in verified tab by uploaded at

- .vscode/settings.json
- android/app/capacitor.build.gradle
- android/app/src/main/assets/capacitor.plugins.json
- android/capacitor.settings.gradle
- ios/App/Podfile
- ios/App/Podfile.lock
- package-lock.json
- package.json
- src/app/features/home/custom-camera/custom-camera.page.html
- src/app/features/home/custom-camera/custom-camera.page.ts
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
Implements [✓ [FR] Disable upload feature on Capture Cam](https://app.asana.com/0/1201016280880500/1206531773468998/f). Here is the [demo](https://app.claap.io/numbers-protocol/fr-disable-upload-feature-on-capture-cam-c-O35CsUM4Uy-JkCri2cmVzyi)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1206640317420272) by [Unito](https://www.unito.io)
> Feature disable upload feature on capture cam

- .vscode/settings.json
On every launch VSCode keep changin codeActionsOnSave from true to `explicit`. Turns out, VSCode true is set to `explicit` since VSCode 1.85.0. It seems boolean values were supported until 1.84.0. https://stackoverflow.com/a/77637765
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1206640289167437) by [Unito](https://www.unito.io)
> chore: Update VSCode formatting settings.

- CHANGELOG.md
- src/app/features/home/details/details.page.ts
- src/app/shared/actions/service/actions.service.ts
- src/app/utils/url.ts
1. Remove authmedia.net from the sharing process. [#3240](https://github.com/numbersprotocol/capture-lite/pull/3240)
​
The issue is also created on [Asana](https://app.asana.com/0/1201016280880500/1207073959210570)
> feat(shared/actions/service): remove authmedia

- src/app/features/home/details/details.page.ts
- src/app/shared/dia-backend/asset/dia-backend-asset-repository.service.ts
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
1. Remove `View asset profile` and move `Share Asset Profile` to the first option in the detail share menu.
​
The issue is also created on [Asana](https://app.asana.com/0/1201016280880500/1207088245078327)
> feat(app/features): remove view asset profile

- src/app/features/home/details/capture-details-with-ionic/capture-details-with-ionic.component.ts
- src/app/utils/url.ts
1. Update the URL format of the asset profile from
`/asset-profile?nid=${nid}` to `/asset-profile/${nid}` [#3242](https://github.com/numbersprotocol/capture-lite/pull/3242)
1. Remove the unused `tmp_token` from the asset profile URL  [#3242](https://github.com/numbersprotocol/capture-lite/pull/3242)
​
┆The issue is also created on [Asana](https://app.asana.com/0/1201016280880500/1207136050658172)
> feat(app/utils/url.ts): update asset profile url

- ios/App/PrivacyInfo.xcprivacy
- src/app/shared/dia-backend/asset/downloading/dia-backend-downloading.service.ts
1. Fix prefetch error caused by incorrect asset information format [#3245](https://github.com/numbersprotocol/capture-lite/pull/3245)
​
┆The issue is also created on [Asana](https://app.asana.com/0/1201016280880500/1207310852515876)
> fix(shared/dia-backend/asset): prefetch error

- src/app/features/home/activities/network-action-order-details/network-action-order-details.page.ts
- src/app/features/home/details/capture-details-with-ionic/capture-details-with-ionic.component.ts
- src/app/features/home/details/details.page.ts
- src/app/features/home/details/information/session/information-session.service.ts
- src/app/shared/dia-backend/asset/dia-backend-asset-repository.service.ts
- src/app/shared/dia-backend/asset/downloading/dia-backend-downloading.service.ts
- src/app/shared/dia-backend/asset/uploading/dia-backend-asset-uploading.service.ts
- src/app/shared/repositories/proof/proof.ts
- src/app/shared/share/share.service.ts
1. Link the asset profile to the parent asset instead of the child asset [#3253](https://github.com/numbersprotocol/capture-lite/pull/3253)
​
┆The issue is also created on [Asana](https://app.asana.com/0/1201016280880500/1208350169750705)
> feat(features/home): link asset profile to parent

- .github/workflows/pre-release.yml
1. Fix the GitHub workflow issue where a deprecated version of actions/upload-artifact is causing a deployment error [#3254](https://github.com/numbersprotocol/capture-lite/pull/3254)
​
┆The issue is also created on [Asana](https://app.asana.com/0/1201016280880500/1208358077009930)
> chore(.github/workflows): fix deploy app error

- src/app/features/home/details/details.page.ts
- src/app/shared/dia-backend/asset/dia-backend-asset-repository.service.ts
- src/app/shared/share/share.service.ts
- src/app/utils/url.ts
- src/assets/i18n/en-us.json
- src/assets/i18n/zh-tw.json
1. Update the share text to "Social Share" and set the share link to the Capture page [#3324](https://github.com/numbersprotocol/capture-lite/pull/3324)
​
┆The issue is also created on [Asana](https://app.asana.com/0/1201016280880500/1209395327570835)
> feat(features/home): update share text and link

- src/app/features/signup/signup.page.ts
Fixes #3246
Rename the variable 'usernameTranlation' to 'usernameTranslation' in the `src/app/features/signup/signup.page.ts` file.
* Rename the variable in the `combineLatest` observable in the constructor.
* Rename the variable in the `createFormFields` method.
* Update the placeholder property in the form field configuration to use the renamed variable.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/numbersprotocol/capture-lite/pull/3327?shareId=db070bbc-1e4f-4205-8765-9d35d6394508).
​
┆The issue is also created on [Asana](https://app.asana.com/1/1200886955782960/project/1201016280880500/task/1209649717928331)
> Rename variable usernameTranlation to usernameTranslation

- .github/workflows/project
Resolves #3330
Set GitHub workflow to add issues to backlog project upon opening
> chore(.github): add new issues to backlog project

- .github/workflows/build-apks.yml
- .github/workflows/build.yml
- .github/workflows/firebase-release.yml
- .github/workflows/pre-release.yml
- set-secret.js
- src/app/features/settings/settings.page.ts
- src/app/shared/dia-backend/auth/dia-backend-auth.service.ts
Ref numbersprotocol/pipedream#11
- Replace Pipedream webhook with backend DELETE /auth/users/me/ endpoint
- Remove unused email parameter from deleteAccount$() method
> feat(auth): migrate account deletion
